In [1]:
import pprint
import pandas
import geopandas
from pandas.io.json import json_normalize
import geojson

import json
import numpy
from czml import czml

In [2]:
with open('../static/data/globe.geo.json') as f:
    data = geojson.load(f)
nestedglobe = pandas.DataFrame(data)
# globe['features'][1]
nestedglobe['features'][0]

{"geometry": {"coordinates": [[[-79.98928788999987, 15.794948635000056], [-79.9878230459999, 15.796210028000074], [-79.98639889199991, 15.794419664000086], [-79.98814856699991, 15.79417552300012], [-79.98928788999987, 15.794948635000056]]], "type": "Polygon"}, "properties": {"abbrev": null, "abbrev_len": 0, "adm0_a3": "BJN", "adm0_a3_is": "-99", "adm0_a3_un": -99, "adm0_a3_us": "B41", "adm0_a3_wb": -99, "adm0_dif": 0, "admin": "Bajo Nuevo Bank (Petrel Is.)", "brk_a3": "B41", "brk_diff": 1, "brk_group": null, "brk_name": "Bajo Nuevo Bank (Petrel Is.)", "continent": "North America", "economy": "7. Least developed region", "featurecla": "Admin-0 country", "filename": "bajonuevobankpetrelis.geojson", "fips_10_": "-99", "formal_en": null, "formal_fr": null, "gdp_md_est": -99, "gdp_year": 2012, "geou_dif": 0, "geounit": "Bajo Nuevo Bank (Petrel Is.)", "gu_a3": "BJN", "homepart": 1, "income_grp": "5. Low income", "iso_a2": "-99", "iso_a3": "-99", "iso_n3": "-99", "labelrank": 8, "lastcensus": -99, "level": 2, "long_len": 32, "mapcolor13": -99, "mapcolor7": 3, "mapcolor8": 7, "mapcolor9": 6, "name": "Bajo Nuevo Bank (Petrel Is.)", "name_alt": null, "name_len": 28, "name_long": "Bajo Nuevo Bank (Petrel Islands)", "name_sort": "Bajo Nuevo Bank (Petrel Is.)", "note_adm0": "Disputed", "note_brk": "Claimed by Columbia, Jamaica, Nicaragua and the United States", "pop_est": -99, "pop_year": 2012, "postal": null, "region_un": "Americas", "region_wb": "Latin America & Caribbean", "scalerank": 6, "sov_a3": "BJN", "sovereignt": "Bajo Nuevo Bank (Petrel Is.)", "su_a3": "BJN", "su_dif": 0, "subregion": "Caribbean", "subunit": "Bajo Nuevo Bank (Petrel Is.)", "tiny": -99, "type": "Indeterminate", "un_a3": "-099", "wb_a2": "-99", "wb_a3": "-99", "wikipedia": -99, "woe_id": -99, "woe_id_eh": -99, "woe_note": "No WOE equivalent."}, "type": "Feature"}

In [24]:
globe = pandas.io.json.json_normalize(nestedglobe['features'])
globe = globe.drop(['properties.abbrev', 'properties.abbrev_len',
              'properties.adm0_a3', 'properties.adm0_a3_is', 'properties.adm0_a3_un',
            'properties.adm0_a3_wb', 'properties.adm0_dif', 'properties.brk_diff',
             'properties.adm0_a3_us', 'properties.brk_a3', 'properties.brk_group',
             'properties.brk_name', 'properties.featurecla', 'properties.tiny',
             'properties.filename', 'properties.fips_10_', 'properties.formal_en',
             'properties.formal_fr', 'properties.gdp_md_est', 'properties.gdp_year',
             'properties.geounit', 'properties.subunit', 'properties.geou_dif', 
             'properties.gu_a3', 'properties.homepart', 'properties.iso_a3', 
              'properties.un_a3', 'properties.wb_a2', 'properties.wb_a3',
             'properties.wikipedia', 'properties.labelrank', 'properties.lastcensus',
             'properties.level', 'properties.sov_a3', 'properties.su_a3',
             'properties.su_dif', 'properties.subregion', 'properties.woe_id', 
             'properties.woe_note', 'properties.woe_id_eh', 'properties.long_len',
             'properties.mapcolor13','properties.mapcolor9','properties.mapcolor8',
             'properties.mapcolor7', 'properties.admin', 'properties.name_alt', 'properties.note_brk',
             'properties.postal', 'properties.pop_est', 'properties.pop_year', 
             'properties.note_brk', 'properties.region_un', 'properties.scalerank',
             'properties.iso_n3', 'properties.name_long', 'properties.name_sort',
             'properties.name_len', 'properties.region_wb', 'properties.note_adm0',
            'properties.continent', 'type'
             ], axis=1)
# df = df.set_index('properties.admin', drop=True)
globe.rename(columns = {'properties.iso_a2': 'properties.code'}, inplace=True)
globe['properties.code'] = globe['properties.code'].astype(str)
globe.sort_values('properties.code').head(250)

,geometry.coordinates,geometry.type,properties.economy,properties.income_grp,properties.code,properties.name,properties.sovereignt,properties.type
0,"[[[-79.98928788999987, 15.794948635000056], [-...",Polygon,7. Least developed region,5. Low income,-99,Bajo Nuevo Bank (Petrel Is.),Bajo Nuevo Bank (Petrel Is.),Indeterminate
41,"[[[123.59701582100011, -12.428317966999899], [...",Polygon,7. Least developed region,5. Low income,-99,Ashmore and Cartier Is.,Australia,Dependency
42,"[[[154.3912866550001, -21.030043226999865], [1...",Polygon,7. Least developed region,5. Low income,-99,Coral Sea Is.,Australia,Dependency
87,"[[[[55.5013126960001, -20.87322356599999], [55...",MultiPolygon,1. Developed region: G7,1. High income: OECD,-99,France,France,Country
94,"[[[20.864700154000047, 43.217337342000036], [2...",Polygon,6. Developing region,4. Lower middle income,-99,Kosovo,Kosovo,Sovereign country
26,"[[[-78.63707434799987, 15.862087307000108], [-...",Polygon,7. Least developed region,5. Low income,-99,Serranilla Bank,Serranilla Bank,Indeterminate
111,"[[[[3.382578972000089, -54.44931405999998], [3...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,-99,Norway,Norway,Sovereign country
160,"[[[48.939111999908164, 11.249129976335054], [4...",Polygon,6. Developing region,4. Lower middle income,-99,Somaliland,Somaliland,Indeterminate
180,"[[[33.905867961000126, 35.09088246600004], [33...",Polygon,2. Developed region: nonG7,2. High income: nonOECD,-99,Dhekelia,United Kingdom,Dependency
182,"[[[[32.626204468000225, 35.165089824000134], [...",MultiPolygon,6. Developing region,3. Upper middle income,-99,N. Cyprus,Northern Cyprus,Sovereign country
183,"[[[[33.92540165200015, 35.06277048700004], [33...",MultiPolygon,6. Developing region,2. High income: nonOECD,-99,Cyprus U.N. Buffer Zone,Cyprus No Mans Area,Indeterminate
40,"[[[[-75.18395510799986, 19.93359416400007], [-...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,-99,USNB Guantanamo Bay,Cuba,Lease
192,"[[[63.3839136150001, 45.56582448300014], [63.3...",Polygon,2. Developed region: nonG7,3. Upper middle income,-99,Baikonur,Kazakhstan,Lease
187,"[[[[96.9139103520001, -12.194512627999854], [9...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,-99,Indian Ocean Ter.,Australia,Dependency
218,"[[[117.753887178, 15.154369263000063], [117.75...",Polygon,7. Least developed region,5. Low income,-99,Scarborough Reef,Scarborough Reef,Indeterminate
228,"[[[32.84080876400009, 34.69946744100013], [32....",Polygon,2. Developed region: nonG7,2. High income: nonOECD,-99,Akrotiri,United Kingdom,Dependency
206,"[[[[114.37647545700004, 9.68012116100013], [11...",MultiPolygon,7. Least developed region,5. Low income,-99,Spratly Is.,Spratly Islands,Indeterminate
195,"[[[76.97641727700011, 35.57865631200005], [77....",Polygon,6. Developing region,4. Lower middle income,-99,Siachen Glacier,Kashmir,Indeterminate
68,"[[[1.707006470000067, 42.5027814740001], [1.69...",Polygon,2. Developed region: nonG7,2. High income: nonOECD,AD,Andorra,Andorra,Sovereign country
178,"[[[[53.863047722, 24.234686591000138], [53.888...",MultiPolygon,6. Developing region,2. High income: nonOECD,AE,United Arab Emirates,United Arab Emirates,Sovereign country
172,"[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,AF,Afghanistan,Afghanistan,Sovereign country
7,"[[[[-61.773019985999916, 17.126532294000143], ...",MultiPolygon,6. Developing region,3. Upper middle income,AG,Antigua and Barb.,Antigua and Barbuda,Sovereign country
1,"[[[[-63.037668423999946, 18.212958075000028], ...",MultiPolygon,6. Developing region,3. Upper middle income,AI,Anguilla,United Kingdom,Dependency
69,"[[[19.747765747000074, 42.57890085900007], [19...",Polygon,6. Developing region,4. Lower middle income,AL,Albania,Albania,Sovereign country
174,"[[[[45.54717289200002, 40.62155263300009], [45...",MultiPolygon,6. Developing region,4. Lower middle income,AM,Armenia,Armenia,Sovereign country
116,"[[[[11.73751945100014, -16.692577982999833], [...",MultiPolygon,7. Least developed region,3. Upper middle income,AO,Angola,Angola,Sovereign country
232,"[[[[-68.65412350199998, -54.88624439899996], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,AR,Argentina,Argentina,Sovereign country
39,"[[[[-168.16047115799995, -14.520928643999968],...",MultiPolygon,6. Developing region,3. Upper middle income,AS,American Samoa,United States of America,Dependency
71,"[[[15.161792440000113, 48.93722076400007], [15...",Polygon,2. Developed region: nonG7,1. High income: OECD,AT,Austria,Austria,Sovereign country
55,"[[[[158.86573326900012, -54.749932549999826], ...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,AU,Australia,Australia,Country
...,...,...,...,...,...,...,...,...
222,"[[[[99.247813347, 6.57485586100016], [99.26026...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,TH,Thailand,Thailand,Sovereign country
220,"[[[[70.61990604700006, 39.85069529200014], [70...",MultiPolygon,6. Developing region,5. Low income,TJ,Tajikistan,Tajikistan,Sovereign country
221,"[[[[124.35455896000016, -9.364181823999871], [...",MultiPolygon,7. Least developed region,4. Lower middle income,TL,Timor-Leste,East Timor,Sovereign country
224,"[[[[53.10206139400006, 38.755072333], [53.0947...",MultiPolygon,6. Developing region,3. Upper middle income,TM,Turkmenistan,Turkmenistan,Sovereign country
165,"[[[[10.929942254000082, 33.896307684000035], [...",MultiPolygon,6. Developing region,3. Upper middle income,TN,Tunisia,Tunisia,Sovereign country
61,"[[[[-176.20702063699989, -22.33879973799992], ...",MultiPolygon,6. Developing region,4. Lower middle income,TO,Tonga,Tonga,Sovereign country
227,"[[[[26.04004967500012, 39.84503815300015], [26...",MultiPolygon,4. Emerging region: MIKT,3. Upper middle income,TR,Turkey,Turkey,Sovereign country
34,"[[[[-60.90729732999998, 10.837144273000163], [...",MultiPolygon,6. Developing region,2. High income: nonOECD,TT,Trinidad and Tobago,Trinidad and Tobago,Sovereign country
60,"[[[[179.90609785200013, -9.418633721999868], [...",MultiPolygon,7. Least developed region,3. Upper middle income,TV,Tuvalu,Tuvalu,Sovereign country
225,"[[[[121.58765709700006, 22.013861395], [121.56...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,TW,Taiwan,Taiwan,Sovereign country
168,"[[[[39.74916454600012, -8.065492432999873], [3...",MultiPolygon,7. Least developed region,5. Low income,TZ,Tanzania,United Republic of Tanzania,Sovereign country
113,"[[[[29.807465040000153, 45.614325262000094], [...",MultiPolygon,6. Developing region,4. Lower middle income,UA,Ukraine,Ukraine,Sovereign country
166,"[[[34.10802616400014, 3.868938091000103], [34....",Polygon,7. Least developed region,5. Low income,UG,Uganda,Uganda,Sovereign country
36,"[[[[-160.0124405589999, -0.382094007999925], [...",MultiPolygon,7. Least developed region,5. Low income,UM,U.S. Minor Outlying Is.,United States of America,Dependency
57,"[[[[-155.6065189699999, 20.137955566000144], [...",MultiPolygon,1. Developed region: G7,1. High income: OECD,US,United States,United States of America,Country
240,"[[[-56.90636673999998, -30.108548685999907], [...",Polygon,5. Emerging region: G20,3. Upper middle income,UY,Uruguay,Uruguay,Sovereign country
226,"[[[[71.75730432100013, 39.9030951940001], [71....",MultiPolygon,6. Developing region,4. Lower middle income,UZ,Uzbekistan,Uzbekistan,Sovereign country
115,"[[[12.45313691700008, 41.902751941000105], [12...",Polygon,2. Developed region: nonG7,2. High income: nonOECD,VA,Vatican,Vatican,Sovereign country
37,"[[[[-61.43272864499988, 12.587836005000113], [...",MultiPolygon,6. Developing region,3. Upper middle income,VC,St. Vin. and Gren.,Saint Vincent and the Grenadines,Sovereign country
243,"[[[[-61.39027141599987, 8.580580853000143], [-...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,VE,Venezuela,Venezuela,Sovereign country
38,"[[[[-64.56786048099994, 18.337388414000046], [...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,VG,British Virgin Is.,United Kingdom,Dependency
43,"[[[[-64.73078365799995, 17.765285549000126], [...",MultiPolygon,6. Developing region,2. High income: nonOECD,VI,U.S. Virgin Is.,United States of America,Dependency
231,"[[[[106.66871178500006, 8.753485419000171], [1...",MultiPolygon,5. Emerging region: G20,4. Lower middle income,VN,Vietnam,Vietnam,Sovereign country
62,"[[[[169.83814537900005, -20.248630466999856], ...",MultiPolygon,7. Least developed region,4. Lower middle income,VU,Vanuatu,Vanuatu,Sovereign country
65,"[[[[-178.0467423169999, -14.312595309999978], ...",MultiPolygon,6. Developing region,4. Lower middle income,WF,Wallis and Futuna Is.,France,Dependency
66,"[[[[-171.5700170559999, -13.938164971999923], ...",MultiPolygon,7. Least developed region,4. Lower middle income,WS,Samoa,Samoa,Sovereign country
229,"[[[[53.308239457000155, 12.11839453700017], [5...",MultiPolygon,7. Least developed region,4. Lower middle income,YE,Yemen,Yemen,Sovereign country
170,"[[[[37.86378014400023, -46.94085051899984], [3...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,ZA,South Africa,South Africa,Sovereign country
169,"[[[31.11983646700014, -8.616630553999912], [31...",Polygon,7. Least developed region,4. Lower middle income,ZM,Zambia,Zambia,Sovereign country
171,"[[[30.010653524000077, -15.64622731499989], [3...",Polygon,5. Emerging region: G20,5. Low income,ZW,Zimbabwe,Zimbabwe,Sovereign country

In [4]:
trafficking = pandas.read_csv('trafficking.csv',low_memory=False)
# trafficking.columns = ['code', 'Year', 'CountryOfExploitation', 'TraffickedGender',
#                        'TraffickedageBroad', 'TraffickedCount'  ]
# trafficking['code'] = trafficking['code'].astype(str)
# trafficking = trafficking.sort_values(['code', 'Year'])


trafficking = trafficking.drop(trafficking.columns[[0, 2]], axis=1)
trafficking = trafficking.replace(['-99','18--20', '24--26', '30--38', '21--23',
                           '27--29', '9--17','39--47', '48+', '0--8',
                           'Unknown'], ['Unknown','Adult-', 'Adult', 'Adult', 'Adult',
                                        'Adult', 'Youth', 'Adult', 'Adult+', 'Youth', 
                                            'ZZ'])
trafficking = trafficking.rename(columns={'yearOfRegistration':"Year"})
# TraffickingCounts = 


# trafficking = trafficking.set_index('citizenship')
# trafficking.dtypes
# trafficking['Year'] = trafficking['Year'].astype(str)
trafficking = trafficking[['Year', 'gender', 'ageBroad','citizenship','CountryOfExploitation']]
trafficking.head(5)

   Year gender ageBroad citizenship CountryOfExploitation
0  2002     ZZ       ZZ          ZZ                    ZZ
1  2002     ZZ       ZZ          ZZ                    ZZ
2  2002     ZZ       ZZ          ZZ                    ZZ
3  2002     ZZ       ZZ          ZZ                    ZZ
4  2002     ZZ       ZZ          ZZ                    ZZ

In [5]:
traffickingCounts = trafficking.groupby(['citizenship', "Year","CountryOfExploitation"],
                 as_index=False).count().iloc[:,:-1]\

                .rename(columns={'citizenship':'properties.code','gender':'CaseCount'})
#                        .set_index(['citizenship', 'Year']) \
traffickingCounts.head()

  properties.code  Year CountryOfExploitation  CaseCount
0              AF  2013                    AF         12
1              AF  2013                    ZZ         25
2              AF  2014                    AF         72
3              AF  2014                    ZZ        116
4              AF  2015                    SA         14

In [6]:
longcounts = traffickingCounts[['properties.code', "Year"]].drop_duplicates()
for index,row in traffickingCounts.iterrows():

    col = row[2]
    
#     TOTAL
    longcounts.loc[(longcounts['properties.code'] == row[0]) & (longcounts["Year"] == row[1]),
                   "Total"] = traffickingCounts.loc[
                            (traffickingCounts['properties.code'] == row[0]) &
                            (traffickingCounts["Year"] == row[1])]['CaseCount'].sum()

#     EACH COUNTRY

    longcounts.loc[(longcounts['properties.code'] == row[0]) &  (longcounts["Year"] == row[1]),
               col] = traffickingCounts.loc[
                        (traffickingCounts['properties.code'] == row[0]) &
                        (traffickingCounts["Year"] == row[1]) &
                        (traffickingCounts['CountryOfExploitation'] == col)]['CaseCount'].values[0]



longcounts.reset_index().to_json("TraffickingCounts.json", orient="records")

In [7]:
longcounts.iloc[3:]

,properties.code,Year,Total,AF,ZZ,SA,AL,TJ,SN,BG,...,IT,RO,DK,SL,TM,CZ,AT,UZ,VN,MX
5,AL,2005,45.0,NaN,NaN,NaN,45.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,BD,2015,11.0,NaN,NaN,NaN,NaN,11.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,BF,2010,33.0,NaN,NaN,NaN,NaN,NaN,33.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,BG,2005,116.0,NaN,NaN,NaN,NaN,NaN,NaN,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,BG,2007,226.0,NaN,NaN,NaN,NaN,NaN,NaN,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,BO,2012,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,BY,2004,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,BY,2005,292.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,BY,2006,257.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,BY,2007,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,BY,2008,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,BY,2010,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,BY,2011,88.0,NaN,63.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,BY,2012,161.0,NaN,161.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,BY,2013,301.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,BY,2014,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,BY,2015,106.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,BY,2016,114.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,BY,2017,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,CD,2007,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,CI,2007,31.0,NaN,NaN,NaN,NaN,NaN,31.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,CN,2015,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,CN,2016,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,CN,2017,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,CO,2002,74.0,NaN,74.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,CO,2003,37.0,NaN,37.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,CO,2010,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,ER,2014,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,GH,2005,514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,GH,2006,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,UA,2009,328.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,UA,2010,370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,UA,2011,429.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,UA,2012,859.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,UA,2013,638.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,UA,2014,735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,UA,2015,422.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,UA,2016,794.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,UA,2017,1174.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,UA,2018,240.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,UG,2014,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,US,2015,1261.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,US,2016,1529.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,US,2017,1369.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,UZ,2005,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0,NaN,NaN
227,UZ,2011,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,UZ,2013,115.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.0,NaN,NaN
229,UZ,2015,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,UZ,2017,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,VN,2016,15.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,VN,2017,139.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,NaN
236,VN,2018,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,ZZ,2002,13.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,ZZ,2009,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,ZZ,2013,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,ZZ,2014,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0
243,ZZ,2015,2609.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,ZZ,2016,3865.0,NaN,76.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,ZZ,2017,6079.0,NaN,226.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251,ZZ,2018,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Total = traffickingCounts.T.sum().reset_index().rename(columns={0:"TotalTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalFemale = traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('Female')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalFemaleTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalMale = traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('Male')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalMaleTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalChild =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('Child')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalChildTrafficked"})\
# .set_index(['citizenship', 'Year'])


# TotalAdultMinus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('Adult-')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalAdult-Trafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalAdult =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('AdultTraf')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalAdultTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalAdultPlus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('Adult+')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalAdult+Trafficked"})\
# .set_index(['citizenship', 'Year'])


# TotalMaleChild =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('MaleChild')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalMaleChildTrafficked"})\
# .set_index(['citizenship', 'Year'])


# TotalMaleAdultMinus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('MaleAdult-')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalMaleAdult-Trafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalMaleAdult =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('MaleAdultTraf')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalMaleAdultTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalMaleAdultPlus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('MaleAdult+')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalMaleAdult+Trafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalFemaleChild =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('MaleChild')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalFemaleChildTrafficked"})\
# .set_index(['citizenship', 'Year'])


# TotalFemaleAdultMinus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('FemaleAdult-')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalFemaleAdult-Trafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalFemaleAdult =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('FemaleAdultTraf')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalFemaleAdultTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalFemaleAdultPlus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('FemaleAdult+')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalFemaleAdult+Trafficked"})\
# .set_index(['citizenship', 'Year'])


# FinalTotals = pandas.concat([Total, TotalChild, TotalAdult,
#                  TotalAdultMinus, TotalAdultPlus, TotalFemale, TotalMale,
#                  TotalMaleChild, TotalMaleAdultMinus, TotalMaleAdult, TotalMaleAdultPlus,
#                 TotalFemaleChild,TotalFemaleAdultMinus, TotalFemaleAdult, TotalFemaleAdultPlus],axis=1, join='outer')

In [9]:
# FinalTrafficking = pandas.concat([FinalTotals, traffickingCounts], axis=1, join='outer')

# FinalTrafficking = FinalTrafficking.reset_index().rename(columns={'citizenship': 'properties.code'})
# FinalTrafficking.head()

In [10]:
gdp = pandas.read_csv('Countries_GDP_Cleaned.csv')
gdp = pandas.DataFrame(gdp)
gdp = gdp.rename(columns={'Country Code':'properties.code'})
# gdp['properties.code'] = gdp['properties.code'].apply(str)
# gdp = gdp.replace('..', -99)
# gdp['GDP'] = gdp['GDP'].apply(float)
gdp = gdp.rename(columns={'GPD Values':'GDP(ppp)', 'Country Name':'Name', "Years":'Year'})
# gdp.dtypes
gdp.tail(100)

                    Name properties.code  Year      GDP(ppp)
5920  West Bank and Gaza              PS  2002  9.322845e+09
5921  West Bank and Gaza              PS  2003  1.042112e+10
5922  West Bank and Gaza              PS  2004  1.162812e+10
5923  West Bank and Gaza              PS  2005  1.331528e+10
5924  West Bank and Gaza              PS  2006  1.309528e+10
5925  West Bank and Gaza              PS  2007  1.321161e+10
5926  West Bank and Gaza              PS  2008  1.248057e+10
5927  West Bank and Gaza              PS  2009  1.497595e+10
5928  West Bank and Gaza              PS  2010  1.558107e+10
5929  West Bank and Gaza              PS  2011  1.710758e+10
5930  West Bank and Gaza              PS  2012  1.995528e+10
5931  West Bank and Gaza              PS  2013  1.940967e+10
5932  West Bank and Gaza              PS  2014  1.954238e+10
5933  West Bank and Gaza              PS  2015  2.219579e+10
5934  West Bank and Gaza              PS  2016  2.325719e+10
5935  West Bank and Gaza              PS  2017  2.288674e+10
5936         Yemen, Rep.              YE  1990  2.592765e+10
5937         Yemen, Rep.              YE  1991  2.847673e+10
5938         Yemen, Rep.              YE  1992  3.151640e+10
5939         Yemen, Rep.              YE  1993  3.355755e+10
5940         Yemen, Rep.              YE  1994  3.657542e+10
5941         Yemen, Rep.              YE  1995  3.945511e+10
5942         Yemen, Rep.              YE  1996  4.203750e+10
5943         Yemen, Rep.              YE  1997  4.499364e+10
5944         Yemen, Rep.              YE  1998  4.821390e+10
5945         Yemen, Rep.              YE  1999  5.079991e+10
5946         Yemen, Rep.              YE  2000  5.516774e+10
5947         Yemen, Rep.              YE  2001  5.857117e+10
5948         Yemen, Rep.              YE  2002  6.181060e+10
5949         Yemen, Rep.              YE  2003  6.540562e+10
...                  ...             ...   ...           ...
5990              Zambia              ZM  2016  6.534790e+10
5991              Zambia              ZM  2017  6.923570e+10
5992            Zimbabwe              ZW  1990  1.715051e+10
5993            Zimbabwe              ZW  1991  1.870168e+10
5994            Zimbabwe              ZW  1992  1.740350e+10
5995            Zimbabwe              ZW  1993  1.800492e+10
5996            Zimbabwe              ZW  1994  2.008626e+10
5997            Zimbabwe              ZW  1995  2.053760e+10
5998            Zimbabwe              ZW  1996  2.307921e+10
5999            Zimbabwe              ZW  1997  2.410346e+10
6000            Zimbabwe              ZW  1998  2.506802e+10
6001            Zimbabwe              ZW  1999  2.524349e+10
6002            Zimbabwe              ZW  2000  2.502810e+10
6003            Zimbabwe              ZW  2001  2.596698e+10
6004            Zimbabwe              ZW  2002  2.402064e+10
6005            Zimbabwe              ZW  2003  2.033590e+10
6006            Zimbabwe              ZW  2004  1.968159e+10
6007            Zimbabwe              ZW  2005  1.915467e+10
6008            Zimbabwe              ZW  2006  1.905975e+10
6009            Zimbabwe              ZW  2007  1.885214e+10
6010            Zimbabwe              ZW  2008  1.582563e+10
6011            Zimbabwe              ZW  2009  1.786244e+10
6012            Zimbabwe              ZW  2010  2.035533e+10
6013            Zimbabwe              ZW  2011  2.398453e+10
6014            Zimbabwe              ZW  2012  2.803645e+10
6015            Zimbabwe              ZW  2013  3.006463e+10
6016            Zimbabwe              ZW  2014  3.125517e+10
6017            Zimbabwe              ZW  2015  3.212793e+10
6018            Zimbabwe              ZW  2016  3.273816e+10
6019            Zimbabwe              ZW  2017  3.447604e+10

[100 rows x 4 columns]

In [11]:
 def colorPick(gdp_md_est):
        
# THESE COLORS DONT SEEM TO MATCH...CHECK US COLORS BELOW

# divided 190 countries into 7 equal categories
     
#     (190.0, 166.375, 142.75, 119.125, 95.5, 71.875, 48.25, 24.625, 1.0)
#  GDP(ppp) categories based on 2017 numbers

    if gdp_md_est > 1088982:
        color = "CHARTREUSE"
    elif gdp_md_est > 367301:
        color = "PALEGREEN"
    elif gdp_md_est > 171588:
        color = "SKYBLUE"
    elif gdp_md_est > 71926:
        color = "PALEVIOLETRED"
    elif gdp_md_est > 34633:
        color = "SANDYBROWN"
    elif gdp_md_est > 19688:
        color = "ORANGERED"
    elif gdp_md_est > 3165:
        color = "RED"
    elif type(gdp_md_est) != "float64":
        color = "Black"
    
    
    else:
        color = 'slategrey'

    return color

In [12]:
gdp.dtypes

Name                object
properties.code     object
Year                 int64
GDP(ppp)           float64
dtype: object

In [13]:
for index,row in gdp.iterrows():
    gdp['properties.color'] = gdp['GDP(ppp)'].apply(colorPick)
gdp.head(5)
gdp[gdp['properties.code']=='US']

               Name properties.code  Year      GDP(ppp) properties.color
5712  United States              US  1990  5.979590e+12       CHARTREUSE
5713  United States              US  1991  6.174040e+12       CHARTREUSE
5714  United States              US  1992  6.539300e+12       CHARTREUSE
5715  United States              US  1993  6.878720e+12       CHARTREUSE
5716  United States              US  1994  7.308760e+12       CHARTREUSE
5717  United States              US  1995  7.664060e+12       CHARTREUSE
5718  United States              US  1996  8.100200e+12       CHARTREUSE
5719  United States              US  1997  8.608520e+12       CHARTREUSE
5720  United States              US  1998  9.089170e+12       CHARTREUSE
5721  United States              US  1999  9.660620e+12       CHARTREUSE
5722  United States              US  2000  1.028480e+13       CHARTREUSE
5723  United States              US  2001  1.062180e+13       CHARTREUSE
5724  United States              US  2002  1.097750e+13       CHARTREUSE
5725  United States              US  2003  1.151070e+13       CHARTREUSE
5726  United States              US  2004  1.227490e+13       CHARTREUSE
5727  United States              US  2005  1.309370e+13       CHARTREUSE
5728  United States              US  2006  1.385590e+13       CHARTREUSE
5729  United States              US  2007  1.447760e+13       CHARTREUSE
5730  United States              US  2008  1.471860e+13       CHARTREUSE
5731  United States              US  2009  1.441870e+13       CHARTREUSE
5732  United States              US  2010  1.496440e+13       CHARTREUSE
5733  United States              US  2011  1.551790e+13       CHARTREUSE
5734  United States              US  2012  1.615530e+13       CHARTREUSE
5735  United States              US  2013  1.669150e+13       CHARTREUSE
5736  United States              US  2014  1.742760e+13       CHARTREUSE
5737  United States              US  2015  1.812070e+13       CHARTREUSE
5738  United States              US  2016  1.862450e+13       CHARTREUSE
5739  United States              US  2017  1.939060e+13       CHARTREUSE

In [34]:
TraffickedWithGdp = pandas.merge(longcounts,gdp, on=['properties.code', 'Year'],
                                 how='left').sort_values(['properties.code'])
# .drop("Year_y", axis=1)

TraffickedWithGdp.head(25)
longcounts[longcounts['properties.code']=='US']

,properties.code,Year,Total,AF,ZZ,SA,AL,TJ,SN,BG,...,IT,RO,DK,SL,TM,CZ,AT,UZ,VN,MX
223,US,2015,1261.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,US,2016,1529.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,US,2017,1369.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

[{k:v for k,v in m.items() if pandas.notnull(v)} for m in TraffickedWithGdp.iloc[:,:-3].to_dict(orient='rows')]

In [40]:
TraffickedWithGdp['TraffickingStats'] = [{k:v for k,v in m.items()  \
                                      if pandas.notnull(v)} for m in \
                                     TraffickedWithGdp.iloc[:,2:-3].to_dict(orient='rows')]
TraffickedWithGdp = TraffickedWithGdp.drop(TraffickedWithGdp.iloc[:,2:-3], axis=1)
TraffickedWithGdp.to_json("../static/data/TraffickingGDPCounts.json",
                                 orient="records")

In [42]:
TraffickedWithGdp['Interval'] = TraffickedWithGdp['Year'].apply(
    lambda x: str(x) + '-01-01T00:00:00.000Z' + '/' + str(x) + '-12-31T23:59:59.999Z')
TraffickedWithGdp = TraffickedWithGdp.drop('Year', axis=1)
TraffickedWithGdp.head()

,properties.code,GDP(ppp),properties.color,TrafficingStats,Interval
0,AF,6.070782e+10,CHARTREUSE,"{'ZZ': 25.0, 'AF': 12.0, 'Total': 37.0}",2013-01-01T00:00:00.000Z/2013-12-31T23:59:59.999Z
1,AF,6.345999e+10,CHARTREUSE,"{'ZZ': 116.0, 'AF': 72.0, 'Total': 188.0}",2014-01-01T00:00:00.000Z/2014-12-31T23:59:59.999Z
2,AF,6.498854e+10,CHARTREUSE,"{'Total': 14.0, 'SA': 14.0}",2015-01-01T00:00:00.000Z/2015-12-31T23:59:59.999Z
3,AL,1.789692e+10,CHARTREUSE,"{'AL': 45.0, 'Total': 45.0}",2005-01-01T00:00:00.000Z/2005-12-31T23:59:59.999Z
4,BD,5.377270e+11,CHARTREUSE,"{'TJ': 11.0, 'Total': 11.0}",2015-01-01T00:00:00.000Z/2015-12-31T23:59:59.999Z

In [16]:
globe.head()

,geometry.coordinates,geometry.type,properties.economy,properties.income_grp,properties.code,properties.name,properties.sovereignt,properties.type
0,"[[[-79.98928788999987, 15.794948635000056], [-...",Polygon,7. Least developed region,5. Low income,-99,Bajo Nuevo Bank (Petrel Is.),Bajo Nuevo Bank (Petrel Is.),Indeterminate
1,"[[[[-63.037668423999946, 18.212958075000028], ...",MultiPolygon,6. Developing region,3. Upper middle income,AI,Anguilla,United Kingdom,Dependency
2,"[[[-62.83885657499987, 17.88198476800008], [-6...",Polygon,2. Developed region: nonG7,1. High income: OECD,BL,St-Barthélemy,France,Dependency
3,"[[[-69.9969376289999, 12.577582098000036], [-6...",Polygon,6. Developing region,2. High income: nonOECD,AW,Aruba,Netherlands,Country
4,"[[[-59.42690995999987, 13.160386460000069], [-...",Polygon,6. Developing region,2. High income: nonOECD,BB,Barbados,Barbados,Sovereign country

In [26]:
globeFinal = pandas.merge(TraffickedWithGdp, globe, on="properties.code", how="outer")
globeFinal['GDP(ppp)'] = globeFinal['GDP(ppp)'].fillna(-99)
globeFinal['properties.color'] = globeFinal['properties.color'].fillna("slategrey")
globeFinal.head(250)

,properties.code,Year,GDP(ppp),properties.color,TraffickDict,geometry.coordinates,geometry.type,properties.economy,properties.income_grp,properties.name,properties.sovereignt,properties.type
0,AF,2013.0,6.070782e+10,CHARTREUSE,"{'ZZ': 25.0, 'AF': 12.0, 'Total': 37.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country
1,AF,2014.0,6.345999e+10,CHARTREUSE,"{'ZZ': 116.0, 'AF': 72.0, 'Total': 188.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country
2,AF,2015.0,6.498854e+10,CHARTREUSE,"{'Total': 14.0, 'SA': 14.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country
3,AL,2005.0,1.789692e+10,CHARTREUSE,"{'AL': 45.0, 'Total': 45.0}","[[[19.747765747000074, 42.57890085900007], [19...",Polygon,6. Developing region,4. Lower middle income,Albania,Albania,Sovereign country
4,BD,2015.0,5.377270e+11,CHARTREUSE,"{'TJ': 11.0, 'Total': 11.0}","[[[[91.9387313160001, 21.714829820000105], [91...",MultiPolygon,7. Least developed region,5. Low income,Bangladesh,Bangladesh,Sovereign country
5,BF,2010.0,2.176280e+10,CHARTREUSE,"{'SN': 33.0, 'Total': 33.0}","[[[-0.3976712649999, 15.002134501000072], [-0....",Polygon,7. Least developed region,5. Low income,Burkina Faso,Burkina Faso,Sovereign country
6,BG,2005.0,7.820818e+10,CHARTREUSE,"{'BG': 116.0, 'Total': 116.0}","[[[22.919561808000054, 43.83422475200007], [23...",Polygon,2. Developed region: nonG7,3. Upper middle income,Bulgaria,Bulgaria,Sovereign country
7,BG,2007.0,9.657048e+10,CHARTREUSE,"{'BG': 226.0, 'Total': 226.0}","[[[22.919561808000054, 43.83422475200007], [23...",Polygon,2. Developed region: nonG7,3. Upper middle income,Bulgaria,Bulgaria,Sovereign country
8,BO,2012.0,6.040646e+10,CHARTREUSE,"{'Total': 18.0, 'AR': 18.0}","[[[-65.29246984899994, -11.50472300199992], [-...",Polygon,5. Emerging region: G20,4. Lower middle income,Bolivia,Bolivia,Sovereign country
9,BY,2017.0,1.792040e+11,CHARTREUSE,"{'RU': 30.0, 'Total': 30.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
10,BY,2016.0,1.718740e+11,CHARTREUSE,"{'RU': 114.0, 'Total': 114.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
11,BY,2015.0,1.741070e+11,CHARTREUSE,"{'BY': 22.0, 'RU': 84.0, 'Total': 106.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
12,BY,2014.0,1.790980e+11,CHARTREUSE,"{'BY': 58.0, 'Total': 58.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
13,BY,2013.0,1.729600e+11,CHARTREUSE,"{'BY': 301.0, 'Total': 301.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
14,BY,2011.0,1.626230e+11,CHARTREUSE,"{'RU': 25.0, 'ZZ': 63.0, 'Total': 88.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
15,BY,2012.0,1.684860e+11,CHARTREUSE,"{'ZZ': 161.0, 'Total': 161.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
16,BY,2008.0,1.370430e+11,CHARTREUSE,"{'RU': 11.0, 'Total': 11.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
17,BY,2007.0,1.219660e+11,CHARTREUSE,"{'RU': 26.0, 'Total': 26.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
18,BY,2006.0,1.093960e+11,CHARTREUSE,"{'RU': 245.0, 'PL': 12.0, 'Total': 257.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
19,BY,2005.0,9.648639e+10,CHARTREUSE,"{'RU': 217.0, 'AE': 64.0, 'PL': 11.0, 'Total':...","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
20,BY,2004.0,8.544660e+10,CHARTREUSE,"{'RU': 35.0, 'AE': 12.0, 'Total': 59.0, 'CY': ...","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
21,BY,2010.0,1.509640e+11,CHARTREUSE,"{'RU': 14.0, 'Total': 14.0}","[[[28.148906697000115, 56.14241404300008], [28...",Polygon,6. Developing region,3. Upper middle income,Belarus,Belarus,Sovereign country
22,CD,2007.0,3.429662e+10,CHARTREUSE,"{'Total': 53.0, 'UG': 53.0}","[[[[12.994589909000126, -5.868244252999901], [...",MultiPolygon,7. Least developed region,5. Low income,Dem. Rep. Congo,Democratic Republic of the Congo,Sovereign country
23,CI,2007.0,4.787468e+10,CHARTREUSE,"{'SN': 31.0, 'Total': 31.0}","[[[[-3.1849666009999, 5.132269598000107], [-3....",MultiPolygon,6. Developing region,4. Lower middle income,Côte d'Ivoire,Ivory Coast,Sovereign country
24,CN,2015.0,1.981430e+13,CHARTREUSE,"{'US': 27.0, 'Total': 27.0}","[[[[111.20460045700011, 15.779242255000055], [...",MultiPolygon,3. Emerging region: BRIC,3. Upper middle income,China,China,Country
25,CN,2016.0,2.141150e+13,CHARTREUSE,"{'US': 52.0, 'Total': 52.0}","[[[[111.20460045700011, 15.779242255000055], [...",MultiPolygon,3. Emerging region: BRIC,3. Upper middle income,China,China,Country
26,CN,2017.0,2.330080e+13,CHARTREUSE,"{'US': 36.0, 'Total': 36.0}","[[[[111.20460045700011, 15.779242255000055], [...",MultiPolygon,3. Emerging region: BRIC,3. Upper middle income,China,China,Country
27,CO,2002.0,2.879860e+11,CHARTREUSE,"{'ZZ': 74.0, 'Total': 74.0}","[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,Colombia,Colombia,Sovereign country
28,CO,2003.0,3.052380e+11,CHARTREUSE,"{'ZZ': 37.0, 'Total': 37.0}","[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,Colombia,Colombia,Sovereign country
29,CO,2010.0,4.904050e+11,CHARTREUSE,"{'Total': 13.0, 'EC': 13.0}","[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,Colombia,Colombia,Sovereign country
...,...,...,...,...,...,...,...,...,...,...,...,...
220,PW,NaN,-9.900000e+01,slategrey,NaN,"[[[[131.81299889400023, 2.960435289000117], [1...",MultiPolygon,6. Developing region,3. Upper middle income,Palau,Palau,Sovereign country
221,PF,NaN,-9.900000e+01,slategrey,NaN,"[[[[-144.31273352799988, -27.640069268999895],...",MultiPolygon,6. Developing region,2. High income: nonOECD,Fr. Polynesia,France,Dependency
222,NZ,NaN,-9.900000e+01,slategrey,NaN,"[[[[169.21275979100002, -52.474562293999895], ...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,New Zealand,New Zealand,Country
223,TV,NaN,-9.900000e+01,slategrey,NaN,"[[[[179.90609785200013, -9.418633721999868], [...",MultiPolygon,7. Least developed region,3. Upper middle income,Tuvalu,Tuvalu,Sovereign country
224,TO,NaN,-9.900000e+01,slategrey,NaN,"[[[[-176.20702063699989, -22.33879973799992], ...",MultiPolygon,6. Developing region,4. Lower middle income,Tonga,Tonga,Sovereign country
225,VU,NaN,-9.900000e+01,slategrey,NaN,"[[[[169.83814537900005, -20.248630466999856], ...",MultiPolygon,7. Least developed region,4. Lower middle income,Vanuatu,Vanuatu,Sovereign country
226,SB,NaN,-9.900000e+01,slategrey,NaN,"[[[[168.81861412900014, -12.284926039999931], ...",MultiPolygon,7. Least developed region,4. Lower middle income,Solomon Is.,Solomon Islands,Sovereign country
227,PG,NaN,-9.900000e+01,slategrey,NaN,"[[[[153.25782311300011, -11.353448174999896], ...",MultiPolygon,6. Developing region,4. Lower middle income,Papua New Guinea,Papua New Guinea,Sovereign country
228,WF,NaN,-9.900000e+01,slategrey,NaN,"[[[[-178.0467423169999, -14.312595309999978], ...",MultiPolygon,6. Developing region,4. Lower middle income,Wallis and Futuna Is.,France,Dependency
229,WS,NaN,-9.900000e+01,slategrey,NaN,"[[[[-171.5700170559999, -13.938164971999923], ...",MultiPolygon,7. Least developed region,4. Lower middle income,Samoa,Samoa,Sovereign country
230,AX,NaN,-9.900000e+01,slategrey,NaN,"[[[[20.920176629000082, 59.909247137000115], [...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,Aland,Finland,Country
231,AD,NaN,-9.900000e+01,slategrey,NaN,"[[[1.707006470000067, 42.5027814740001], [1.69...",Polygon,2. Developed region: nonG7,2. High income: nonOECD,Andorra,Andorra,Sovereign country
232,AT,NaN,-9.900000e+01,slategrey,NaN,"[[[15.161792440000113, 48.93722076400007], [15...",Polygon,2. Developed region: nonG7,1. High income: OECD,Austria,Austria,Sovereign country
233,BA,NaN,-9.900000e+01,slategrey,NaN,"[[[16.941528768000097, 45.241218974], [16.9473...",Polygon,6. Developing region,3. Upper middle income,Bosnia and Herz.,Bosnia and Herzegovina,Sovereign country
234,CH,NaN,-9.900000e+01,slategrey,NaN,"[[[8.61743737800009, 47.75731862400008], [8.62...",Polygon,2. Developed region: nonG7,1. High income: OECD,Switzerland,Switzerland,Sovereign country
235,BE,NaN,-9.900000e+01,slategrey,NaN,"[[[4.815447224000138, 51.431073711000025], [4....",Polygon,2. Developed region: nonG7,1. High income: OECD,Belgium,Belgium,Sovereign country
236,CZ,NaN,-9.900000e+01,slategrey,NaN,"[[[14.39780806400006, 51.01311472600011], [14....",Polygon,2. Developed region: nonG7,1. High income: OECD,Czech Rep.,Czech Republic,Sovereign country
237,DK,NaN,-9.900000e+01,slategrey,NaN,"[[[[11.256032748000107, 54.954575914000046], [...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,Denmark,Denmark,Country
238,ES,NaN,-9.900000e+01,slategrey,NaN,"[[[[-17.885121222999942, 27.797919012000037], ...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,Spain,Spain,Sovereign country
239,DE,NaN,-9.900000e+01,slategrey,NaN,"[[[[6.742198113000114, 53.57835521000014], [6....",MultiPolygon,1. Developed region: G7,1. High income: OECD,Germany,Germany,Sovereign country
240,EE,NaN,-9.900000e+01,slategrey,NaN,"[[[[23.270192905000044, 57.78563060100008], [2...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,Estonia,Estonia,Sovereign country
241,FI,NaN,-9.900000e+01,slategrey,NaN,"[[[[22.443695509000094, 59.85146719000009], [2...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,Finland,Finland,Country
242,FO,NaN,-9.900000e+01,slategrey,NaN,"[[[[-6.887766079999892, 61.622219143000095], [...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,Faeroe Is.,Denmark,Dependency
243,GG,NaN,-9.900000e+01,slategrey,NaN,"[[[[-2.364654100999957, 49.417873440000065], [...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,Guernsey,United Kingdom,Country
244,GB,NaN,-9.900000e+01,slategrey,NaN,"[[[[-6.287505662999904, 49.91400788000006], [-...",MultiPolygon,1. Developed region: G7,1. High income: OECD,United Kingdom,United Kingdom,Country
245,GI,NaN,-9.900000e+01,slategrey,NaN,"[[[-5.358386758763487, 36.1411094470883], [-5....",Polygon,2. Developed region: nonG7,1. High income: OECD,Gibraltar,United Kingdom,Dependency
246,HU,NaN,-9.900000e+01,slategrey,NaN,"[[[20.981488891000083, 48.51685882600006], [21...",Polygon,2. Developed region: nonG7,1. High income: OECD,Hungary,Hungary,Sovereign country
247,HR,NaN,-9.900000e+01,slategrey,NaN,"[[[[16.933929884000094, 42.77094147300012], [1...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,Croatia,Croatia,Sovereign country
248,GR,NaN,-9.900000e+01,slategrey,NaN,"[[[[24.135264519000145, 34.821763414000074], [...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,Greece,Greece,Sovereign country
249,IE,NaN,-9.900000e+01,slategrey,NaN,"[[[[-9.82408606699994, 51.638902085000076], [-...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,Ireland,Ireland,Sovereign country

In [43]:
# Source: 
# https://github.com/gboeing/urban-data-science/blob/3faf7e028d48cb03ddb999c5a910213c5384e7dc/17-Leaflet-Web-Mapping/leaflet-simple-demo/pandas-to-geojson.ipynb
def df_to_geojson(df, properties):
    geojson = {'type':'FeatureCollection', 'features':[]}
    for _, row in df.iterrows():
        feature = {'type':'Feature',
                   'properties':{},
                   'geometry':{'type': [],'coordinates':[]}}
        feature['geometry']['coordinates'] = row['geometry.coordinates']
        feature['geometry']['type'] = row['geometry.type']
        for prop in properties:
            feature['properties'][prop] = row[prop]
        geojson['features'].append(feature)
    return geojson

cols = ['properties.code', 
        'Interval', 'GDP(ppp)', 'properties.color','TraffickingStats',
       'properties.economy', 'properties.income_grp', 'properties.name',
       'properties.sovereignt', 'properties.type']

In [44]:
with open('../static/data/globe2.geo.json', 'w', encoding='utf-8') as f:
    json.dump(df_to_geojson(globeFinal.head(25), cols), f, ensure_ascii=False)

KeyError: 'Interval'

In [31]:
globeFinal['TraffickDict']

0                {'ZZ': 25.0, 'AF': 12.0, 'Total': 37.0}
1              {'ZZ': 116.0, 'AF': 72.0, 'Total': 188.0}
2                            {'Total': 14.0, 'SA': 14.0}
3                            {'AL': 45.0, 'Total': 45.0}
4                            {'TJ': 11.0, 'Total': 11.0}
5                            {'SN': 33.0, 'Total': 33.0}
6                          {'BG': 116.0, 'Total': 116.0}
7                          {'BG': 226.0, 'Total': 226.0}
8                            {'Total': 18.0, 'AR': 18.0}
9                            {'RU': 30.0, 'Total': 30.0}
10                         {'RU': 114.0, 'Total': 114.0}
11              {'BY': 22.0, 'RU': 84.0, 'Total': 106.0}
12                           {'BY': 58.0, 'Total': 58.0}
13                         {'BY': 301.0, 'Total': 301.0}
14               {'RU': 25.0, 'ZZ': 63.0, 'Total': 88.0}
15                         {'ZZ': 161.0, 'Total': 161.0}
16                           {'RU': 11.0, 'Total': 11.0}
17                           {'RU': 26.0, 'Total': 26.0}
18             {'RU': 245.0, 'PL': 12.0, 'Total': 257.0}
19     {'RU': 217.0, 'AE': 64.0, 'PL': 11.0, 'Total':...
20     {'RU': 35.0, 'AE': 12.0, 'Total': 59.0, 'CY': ...
21                           {'RU': 14.0, 'Total': 14.0}
22                           {'Total': 53.0, 'UG': 53.0}
23                           {'SN': 31.0, 'Total': 31.0}
24                           {'US': 27.0, 'Total': 27.0}
25                           {'US': 52.0, 'Total': 52.0}
26                           {'US': 36.0, 'Total': 36.0}
27                           {'ZZ': 74.0, 'Total': 74.0}
28                           {'ZZ': 37.0, 'Total': 37.0}
29                           {'Total': 13.0, 'EC': 13.0}
                             ...
324                                                  NaN
325                                                  NaN
326                                                  NaN
327                                                  NaN
328                                                  NaN
329                                                  NaN
330                                                  NaN
331                                                  NaN
332                                                  NaN
333                                                  NaN
334                                                  NaN
335                                                  NaN
336                                                  NaN
337                                                  NaN
338                                                  NaN
339                                                  NaN
340                                                  NaN
341                                                  NaN
342                                                  NaN
343                                                  NaN
344                                                  NaN
345                                                  NaN
346                                                  NaN
347                                                  NaN
348                                                  NaN
349                                                  NaN
350                                                  NaN
351                                                  NaN
352                                                  NaN
353                                                  NaN
Name: TraffickDict, Length: 354, dtype: object

In [27]:
 globeFinal[globeFinal.isnull().any(axis=1)]

,properties.code,Year,GDP(ppp),properties.color,TraffickDict,geometry.coordinates,geometry.type,properties.economy,properties.income_grp,properties.name,properties.sovereignt,properties.type
146,ZZ,2002.0,-99.0,slategrey,"{'ZZ': 13.0, 'Total': 13.0}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,ZZ,2009.0,-99.0,slategrey,"{'TT': 11.0, 'Total': 41.0, 'EC': 30.0}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,ZZ,2013.0,-99.0,slategrey,"{'Total': 29.0, 'EC': 11.0, 'AR': 18.0}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,ZZ,2014.0,-99.0,slategrey,"{'MX': 13.0, 'Total': 13.0}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,ZZ,2015.0,-99.0,slategrey,"{'US': 2570.0, 'ZZ': 25.0, 'Total': 2609.0, 'C...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,ZZ,2016.0,-99.0,slategrey,"{'US': 3789.0, 'ZZ': 76.0, 'Total': 3865.0}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,ZZ,2017.0,-99.0,slategrey,"{'US': 5782.0, 'ZZ': 226.0, 'KH': 71.0, 'Total...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,ZZ,2018.0,-99.0,slategrey,"{'TH': 11.0, 'Total': 11.0}",NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,-99,NaN,-99.0,slategrey,NaN,"[[[-79.98928788999987, 15.794948635000056], [-...",Polygon,7. Least developed region,5. Low income,Bajo Nuevo Bank (Petrel Is.),Bajo Nuevo Bank (Petrel Is.),Indeterminate
155,-99,NaN,-99.0,slategrey,NaN,"[[[-78.63707434799987, 15.862087307000108], [-...",Polygon,7. Least developed region,5. Low income,Serranilla Bank,Serranilla Bank,Indeterminate
156,-99,NaN,-99.0,slategrey,NaN,"[[[[-75.18395510799986, 19.93359416400007], [-...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,USNB Guantanamo Bay,Cuba,Lease
157,-99,NaN,-99.0,slategrey,NaN,"[[[123.59701582100011, -12.428317966999899], [...",Polygon,7. Least developed region,5. Low income,Ashmore and Cartier Is.,Australia,Dependency
158,-99,NaN,-99.0,slategrey,NaN,"[[[154.3912866550001, -21.030043226999865], [1...",Polygon,7. Least developed region,5. Low income,Coral Sea Is.,Australia,Dependency
159,-99,NaN,-99.0,slategrey,NaN,"[[[[55.5013126960001, -20.87322356599999], [55...",MultiPolygon,1. Developed region: G7,1. High income: OECD,France,France,Country
160,-99,NaN,-99.0,slategrey,NaN,"[[[20.864700154000047, 43.217337342000036], [2...",Polygon,6. Developing region,4. Lower middle income,Kosovo,Kosovo,Sovereign country
161,-99,NaN,-99.0,slategrey,NaN,"[[[[3.382578972000089, -54.44931405999998], [3...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,Norway,Norway,Sovereign country
162,-99,NaN,-99.0,slategrey,NaN,"[[[48.939111999908164, 11.249129976335054], [4...",Polygon,6. Developing region,4. Lower middle income,Somaliland,Somaliland,Indeterminate
163,-99,NaN,-99.0,slategrey,NaN,"[[[33.905867961000126, 35.09088246600004], [33...",Polygon,2. Developed region: nonG7,2. High income: nonOECD,Dhekelia,United Kingdom,Dependency
164,-99,NaN,-99.0,slategrey,NaN,"[[[[32.626204468000225, 35.165089824000134], [...",MultiPolygon,6. Developing region,3. Upper middle income,N. Cyprus,Northern Cyprus,Sovereign country
165,-99,NaN,-99.0,slategrey,NaN,"[[[[33.92540165200015, 35.06277048700004], [33...",MultiPolygon,6. Developing region,2. High income: nonOECD,Cyprus U.N. Buffer Zone,Cyprus No Mans Area,Indeterminate
166,-99,NaN,-99.0,slategrey,NaN,"[[[[96.9139103520001, -12.194512627999854], [9...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,Indian Ocean Ter.,Australia,Dependency
167,-99,NaN,-99.0,slategrey,NaN,"[[[63.3839136150001, 45.56582448300014], [63.3...",Polygon,2. Developed region: nonG7,3. Upper middle income,Baikonur,Kazakhstan,Lease
168,-99,NaN,-99.0,slategrey,NaN,"[[[76.97641727700011, 35.57865631200005], [77....",Polygon,6. Developing region,4. Lower middle income,Siachen Glacier,Kashmir,Indeterminate
169,-99,NaN,-99.0,slategrey,NaN,"[[[[114.37647545700004, 9.68012116100013], [11...",MultiPolygon,7. Least developed region,5. Low income,Spratly Is.,Spratly Islands,Indeterminate
170,-99,NaN,-99.0,slategrey,NaN,"[[[117.753887178, 15.154369263000063], [117.75...",Polygon,7. Least developed region,5. Low income,Scarborough Reef,Scarborough Reef,Indeterminate
171,-99,NaN,-99.0,slategrey,NaN,"[[[32.84080876400009, 34.69946744100013], [32....",Polygon,2. Developed region: nonG7,2. High income: nonOECD,Akrotiri,United Kingdom,Dependency
172,AI,NaN,-99.0,slategrey,NaN,"[[[[-63.037668423999946, 18.212958075000028], ...",MultiPolygon,6. Developing region,3. Upper middle income,Anguilla,United Kingdom,Dependency
173,BL,NaN,-99.0,slategrey,NaN,"[[[-62.83885657499987, 17.88198476800008], [-6...",Polygon,2. Developed region: nonG7,1. High income: OECD,St-Barthélemy,France,Dependency
174,AW,NaN,-99.0,slategrey,NaN,"[[[-69.9969376289999, 12.577582098000036], [-6...",Polygon,6. Developing region,2. High income: nonOECD,Aruba,Netherlands,Country
175,BB,NaN,-99.0,slategrey,NaN,"[[[-59.42690995999987, 13.160386460000069], [-...",Polygon,6. Developing region,2. High income: nonOECD,Barbados,Barbados,Sovereign country
...,...,...,...,...,...,...,...,...,...,...,...,...
324,IR,NaN,-99.0,slategrey,NaN,"[[[[55.0543725920003, 25.864610092999968], [55...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,Iran,Iran,Sovereign country
325,KW,NaN,-99.0,slategrey,NaN,"[[[[48.38111412900017, 29.43398672100004], [48...",MultiPolygon,6. Developing region,2. High income: nonOECD,Kuwait,Kuwait,Sovereign country
326,LB,NaN,-99.0,slategrey,NaN,"[[[36.391194296000094, 34.62248728400007], [36...",Polygon,6. Developing region,3. Upper middle income,Lebanon,Lebanon,Sovereign country
327,MO,NaN,-99.0,slategrey,NaN,"[[[[113.55860436300023, 22.163031317], [113.56...",MultiPolygon,6. Developing region,2. High income: nonOECD,Macao,China,Country
328,MN,NaN,-99.0,slategrey,NaN,"[[[100.0059676520001, 51.73172719300007], [100...",Polygon,6. Developing region,4. Lower middle income,Mongolia,Mongolia,Sovereign country
329,OM,NaN,-99.0,slategrey,NaN,"[[[[55.89079837300008, 17.504543361000074], [5...",MultiPolygon,6. Developing region,2. High income: nonOECD,Oman,Oman,Sovereign country
330,MY,NaN,-99.0,slategrey,NaN,"[[[[111.4124455090001, 2.38735586100006], [111...",MultiPolygon,6. Developing region,3. Upper middle income,Malaysia,Malaysia,Sovereign country
331,PK,NaN,-99.0,slategrey,NaN,"[[[[67.47779381600006, 24.051214911000116], [6...",MultiPolygon,5. Emerging region: G20,4. Lower middle income,Pakistan,Pakistan,Sovereign country
332,KP,NaN,-99.0,slategrey,NaN,"[[[[125.31275475400017, 37.74140045800008], [1...",MultiPolygon,7. Least developed region,5. Low income,Dem. Rep. Korea,North Korea,Sovereign country
333,PS,NaN,-99.0,slategrey,NaN,"[[[[34.26439904800023, 31.224193420000073], [3...",MultiPolygon,6. Developing region,4. Lower middle income,Palestine,Israel,Disputed
334,QA,NaN,-99.0,slategrey,NaN,"[[[51.215258294748196, 24.6258503608546], [51....",Polygon,6. Developing region,2. High income: nonOECD,Qatar,Qatar,Sovereign country
335,SA,NaN,-99.0,slategrey,NaN,"[[[[41.89846671200016, 16.751483694000015], [4...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,Saudi Arabia,Saudi Arabia,Sovereign country
336,SG,NaN,-99.0,slategrey,NaN,"[[[103.96078535200013, 1.39109935100015], [103...",Polygon,6. Developing region,2. High income: nonOECD,Singapore,Singapore,Sovereign country
337,TL,NaN,-99.0,slategrey,NaN,"[[[[124.35455896000016, -9.364181823999871], [...",MultiPolygon,7. Least developed region,4. Lower middle income,Timor-Leste,East Timor,Sovereign country
338,SY,NaN,-99.0,slategrey,NaN,"[[[42.2368323160002, 37.28630401600019], [42.2...",Polygon,6. Developing region,4. Lower middle income,Syria,Syria,Sovereign country
339,TW,NaN,-99.0,slategrey,NaN,"[[[[121.58765709700006, 22.013861395], [121.56...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,Taiwan,Taiwan,Sovereign country
340,TR,NaN,-99.0,slategrey,NaN,"[[[[26.04004967500012, 39.84503815300015], [26...",MultiPolygon,4. Emerging region: MIKT,3. Upper middle income,Turkey,Turkey,Sovereign country
341,YE,NaN,-99.0,slategrey,NaN,"[[[[53.308239457000155, 12.11839453700017], [5...",MultiPolygon,7. Least developed region,4. Lower middle income,Yemen,Yemen,Sovereign country
342,AR,NaN,-99.0,slategrey,NaN,"[[[[-68.65412350199998, -54.88624439899996], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,Argentina,Argentina,Sovereign country
343,BR,NaN,-99.0,slategrey,NaN,"[[[[-48.54259192599997, -27.816664320999834], ...",MultiPolygon,3. Emerging region: BRIC,3. Upper middle income,Brazil,Brazil,Sovereign country
344,FK,NaN,-99.0,slategrey,NaN,"[[[[-59.74249485099995, -52.357972579999895], ...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,Falkland Is.,United Kingdom,Dependency
345,PY,NaN,-99.0,slategrey,NaN,"[[[-58.15879675299999, -20.165124612999918], [...",Polygon,5. Emerging region: G20,4. Lower middle income,Paraguay,Paraguay,Sovereign country
346,EC,NaN,-99.0,slategrey,NaN,"[[[[-80.11510169199994, -2.997979424999855], [...",MultiPolygon,6. Developing region,3. Upper middle income,Ecuador,Ecuador,Sovereign country
347,GY,NaN,-99.0,slategrey,NaN,"[[[[-58.44102942599994, 6.904771226000108], [-...",MultiPolygon,6. Developing region,4. Lower middle income,Guyana,Guyana,Sovereign country
348,PE,NaN,-99.0,slategrey,NaN,"[[[[-76.17565995399988, -14.28837484699987], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,Peru,Peru,Sovereign country
349,UY,NaN,-99.0,slategrey,NaN,"[[[-56.90636673999998, -30.108548685999907], [...",Polygon,5. Emerging region: G20,3. Upper middle income,Uruguay,Uruguay,Sovereign country
350,SR,NaN,-99.0,slategrey,NaN,"[[[-54.17096517463119, 5.348376149408466], [-5...",Polygon,6. Developing region,3. Upper middle income,Suriname,Suriname,Sovereign country
351,CL,NaN,-99.0,slategrey,NaN,"[[[[-67.25609290299991, -55.82887135199992], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,Chile,Chile,Sovereign country
352,VE,NaN,-99.0,slategrey,NaN,"[[[[-61.39027141599987, 8.580580853000143], [-...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,Venezuela,Venezuela,Sovereign country
353,CK,NaN,-99.0,slategrey,NaN,"[[[[-157.9151098299999, -21.937676690999865], ...",MultiPolygon,6. Developing region,3. Upper middle income,Cook Is.,New Zealand,Dependency

In [21]:
with open('../static/data/miniGlobe.geo.json', 'w', encoding='utf-8') as f:
    json.dump(df_to_geojson(globe, cols), f, ensure_ascii=False)

KeyError: 'Year'

In [ ]:
df_to_geojson(globe.head(1), cols)

In [ ]:
nestedglobe['features'][0]

In [ ]:
# {
#     "id": "Facility/AGI",
#     "name": "AGI",
#     "availability": "2012-03-15T10:00:00Z/2012-03-16T10:00:00Z",
#     "description": "<p>Analytical Graphics, Inc. (AGI) develops commercial modeling and analysis software.</p>",
#     "billboard": {
#         "eyeOffset": {
#             "cartesian": [ 0, 0, 0 ]
#         },
#         "horizontalOrigin": "CENTER",
#         "image": "",
#         "pixelOffset": {
#             "cartesian2": [ 0, 0 ]
#         },
#         "scale": 1.5,
#         "show": true,
#         "verticalOrigin": "CENTER"
#     },
#     "label": {
#         "fillColor": {
#             "rgba": [ 0, 255, 255, 255 ]
#         },
#         "font": "11pt Lucida Console",
#         "horizontalOrigin": "LEFT",
#         "outlineColor": {
#             "rgba": [ 0, 0, 0, 255 ]
#         },
#         "outlineWidth": 2,
#         "pixelOffset": {
#             "cartesian2": [ 12, 0 ]
#         },
#         "show": true,
#         "style": "FILL_AND_OUTLINE",
#         "text": "AGI",
#         "verticalOrigin": "CENTER"
#     },
#     "position": {
#         "cartesian": [ 1216469.9357990976, -4736121.71856379, 4081386.8856866374 ]
#     }
# }
# {
#     "id": "document",
#     "name": "My Document",
#     "version": "1.0",
#     "clock": {
#         "interval": "2012-03-15T10:00:00Z/2012-03-16T10:00:00Z",
#         "currentTime": "2012-03-15T10:00:00Z",
#         "multiplier": 60,
#         "range": "LOOP_STOP",
#         "step": "SYSTEM_CLOCK_MULTIPLIER"
#     }
# }
# {
#     "id": "InternationalSpaceStation",
#     "position": {
#         "interpolationAlgorithm": "LAGRANGE",
#         "interpolationDegree": 5,
#         "referenceFrame": "INERTIAL",
#         "epoch": "2012-05-02T12:00:00Z",
#         "cartesian": [
#             0.0, -6668447.2211117, 1201886.45913705, 146789.427467256,
#             60.0, -6711432.84684144, 919677.673492462, -214047.552431458,
#             90.0, -6721319.92231553, 776899.784034099, -394198.837519575,
#             150.0, -6717826.447064, 488820.628328182, -752924.980158179,
#             180.0, -6704450.41462847, 343851.784836767, -931084.800346031,
#             240.0, -6654518.44949696, 52891.726433174, -1283967.69137678
#         ]
#     }
# }

# https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Path