In [3]:
import pprint
import pandas
import geopandas
from pandas.io.json import json_normalize
import geojson
import json
import numpy
from functools import reduce

In [4]:
with open('../static/data/globe.geo.json') as f:
    data = geojson.load(f)
globe = pandas.DataFrame(data)
# data[1]

In [5]:
globe = pandas.io.json.json_normalize(data['features'])
globe = globe.drop(['properties.abbrev', 'properties.abbrev_len',
              'properties.adm0_a3', 'properties.adm0_a3_is', 'properties.adm0_a3_un',
            'properties.adm0_a3_wb', 'properties.adm0_dif', 'properties.brk_diff',
             'properties.adm0_a3_us', 'properties.brk_a3', 'properties.brk_group',
             'properties.brk_name', 'properties.featurecla', 'properties.tiny',
             'properties.filename', 'properties.fips_10_', 'properties.formal_en',
             'properties.formal_fr', 'properties.gdp_md_est', 'properties.gdp_year',
             'properties.geounit', 'properties.subunit', 'properties.geou_dif', 
             'properties.gu_a3', 'properties.homepart', 'properties.iso_a3', 
              'properties.un_a3', 'properties.wb_a2', 'properties.wb_a3',
             'properties.wikipedia', 'properties.labelrank', 'properties.lastcensus',
             'properties.level', 'properties.sov_a3', 'properties.su_a3',
             'properties.su_dif', 'properties.subregion', 'properties.woe_id', 
             'properties.woe_note', 'properties.woe_id_eh', 'properties.long_len',
             'properties.mapcolor13','properties.mapcolor9','properties.mapcolor8',
             'properties.mapcolor7', 'properties.admin', 'properties.name_alt', 'properties.note_brk',
             'properties.postal', 'properties.pop_est', 'properties.pop_year', 
             'properties.note_brk', 'properties.region_un', 'properties.scalerank',
             'properties.iso_n3', 'properties.name_long', 'properties.name_sort',
             'properties.name_len', 'properties.region_wb', 'properties.note_adm0',
            'properties.continent', 'type'
             ], axis=1)
# df = df.set_index('properties.admin', drop=True)
globe.rename(columns = {'properties.iso_a2': 'code'}, inplace=True)
globe['code'] = globe['code'].astype(str)
globe.head()

,geometry.coordinates,geometry.type,properties.economy,properties.income_grp,code,properties.name,properties.sovereignt,properties.type
0,"[[[-79.98928788999987, 15.794948635000056], [-...",Polygon,7. Least developed region,5. Low income,-99,Bajo Nuevo Bank (Petrel Is.),Bajo Nuevo Bank (Petrel Is.),Indeterminate
1,"[[[[-63.037668423999946, 18.212958075000028], ...",MultiPolygon,6. Developing region,3. Upper middle income,AI,Anguilla,United Kingdom,Dependency
2,"[[[-62.83885657499987, 17.88198476800008], [-6...",Polygon,2. Developed region: nonG7,1. High income: OECD,BL,St-Barthélemy,France,Dependency
3,"[[[-69.9969376289999, 12.577582098000036], [-6...",Polygon,6. Developing region,2. High income: nonOECD,AW,Aruba,Netherlands,Country
4,"[[[-59.42690995999987, 13.160386460000069], [-...",Polygon,6. Developing region,2. High income: nonOECD,BB,Barbados,Barbados,Sovereign country

In [6]:
trafficking = pandas.read_csv('trafficking.csv',low_memory=False)
# trafficking.columns = ['code', 'Year', 'CountryOfExploitation', 'TraffickedGender',
#                        'TraffickedageBroad', 'TraffickedCount'  ]
# trafficking['code'] = trafficking['code'].astype(str)
# trafficking = trafficking.sort_values(['code', 'Year'])


trafficking = trafficking.drop(trafficking.columns[[0, 2]], axis=1)
trafficking = trafficking.replace(['-99','18--20', '24--26', '30--38', '21--23',
                           '27--29', '9--17','39--47', '48+', '0--8',
                           'Unknown'], ['Unknown','Adult-', 'Adult', 'Adult', 'Adult',
                                        'Adult', 'Youth', 'Adult', 'Adult+', 'Youth', 
                                            'Unknown'])
trafficking = trafficking.rename(columns={'yearOfRegistration':"Year"})
# TraffickingCounts = 


# trafficking = trafficking.set_index('citizenship')
# trafficking.dtypes
# trafficking['Year'] = trafficking['Year'].astype(str)
trafficking = trafficking[['Year', 'gender', 'ageBroad','citizenship','CountryOfExploitation']]
trafficking.head(5)

   Year   gender ageBroad citizenship CountryOfExploitation
0  2002  Unknown  Unknown     Unknown               Unknown
1  2002  Unknown  Unknown     Unknown               Unknown
2  2002  Unknown  Unknown     Unknown               Unknown
3  2002  Unknown  Unknown     Unknown               Unknown
4  2002  Unknown  Unknown     Unknown               Unknown

In [9]:
traffickingCounts = trafficking.groupby(['citizenship', "Year"], as_index=True).sum().iloc[:,:0]
for index,row in trafficking.iterrows():
    col = str(row[4]) + str(row[1]) + str(row[2]) + 'Trafficked'

    if col not in traffickingCounts.columns:
        print(col)
        traffickingCounts[col] = 0

    traffickingCounts.loc[(row[3], row[0]), col] += 1

UnknownUnknownUnknownTrafficked
UnknownFemaleAdult-Trafficked
Y1FemaleAdult-Trafficked
BAFemaleAdult-Trafficked
MKFemaleAdult-Trafficked
UnknownFemaleAdultTrafficked
Y1FemaleAdultTrafficked
BAFemaleAdultTrafficked
MKFemaleAdultTrafficked
MKFemaleYouthTrafficked
UnknownFemaleUnknownTrafficked
UnknownMaleUnknownTrafficked
RUFemaleAdult-Trafficked
MDFemaleAdult-Trafficked
AEFemaleAdultTrafficked
CYFemaleAdultTrafficked
MDFemaleAdultTrafficked
RUFemaleYouthTrafficked
MDFemaleYouthTrafficked
GHFemaleYouthTrafficked
ALFemaleAdult-Trafficked
BGFemaleAdult-Trafficked
AEFemaleAdult-Trafficked
ITFemaleAdult-Trafficked
ROFemaleAdult-Trafficked
TRFemaleAdult-Trafficked
UZFemaleAdult-Trafficked
ALFemaleAdultTrafficked
BGFemaleAdultTrafficked
PLFemaleAdultTrafficked
RUFemaleAdultTrafficked
ROFemaleAdultTrafficked
TJFemaleAdultTrafficked
TRFemaleAdultTrafficked
UZFemaleAdultTrafficked
MYFemaleAdultTrafficked
ALFemaleYouthTrafficked
BGFemaleYouthTrafficked
GHMaleYouthTrafficked
RUMaleAdult-Trafficked
RUMaleAdultTrafficked
RUMaleAdult+Trafficked
RUMaleYouthTrafficked
MYFemaleAdult-Trafficked
CZFemaleAdultTrafficked
IDFemaleAdultTrafficked
MYFemaleYouthTrafficked
ROFemaleYouthTrafficked
PLMaleAdultTrafficked
MDMaleYouthTrafficked
UGFemaleYouthTrafficked
PLFemaleAdult-Trafficked
UAFemaleAdult-Trafficked
UAFemaleAdultTrafficked
ATFemaleAdultTrafficked
SNFemaleYouthTrafficked
UGMaleYouthTrafficked
SNMaleYouthTrafficked
SLFemaleYouthTrafficked
UAFemaleYouthTrafficked
KZMaleAdultTrafficked
UAMaleAdultTrafficked
SLMaleYouthTrafficked
ECUnknownUnknownTrafficked
TTUnknownUnknownTrafficked
MDMaleAdult-Trafficked
THFemaleYouthTrafficked
KZFemaleAdult-Trafficked
ECFemaleAdultTrafficked
TMFemaleAdultTrafficked
MDFemaleAdult+Trafficked
UAFemaleAdult+Trafficked
THMaleYouthTrafficked
SNMaleAdult-Trafficked
UnknownMaleAdultTrafficked
THUnknownYouthTrafficked
UnknownFemaleYouthTrafficked
KZFemaleAdultTrafficked
UnknownFemaleAdult+Trafficked
UnknownMaleYouthTrafficked
UnknownMaleAdult-Trafficked
MDMaleAdultTrafficked
TJMaleAdultTrafficked
UnknownMaleAdult+Trafficked
TJMaleAdult+Trafficked
UAMaleAdult+Trafficked
UAMaleYouthTrafficked
HTFemaleYouthTrafficked
JOFemaleAdultTrafficked
ARFemaleYouthTrafficked
HTMaleYouthTrafficked
ARUnknownUnknownTrafficked
BYFemaleAdultTrafficked
RUFemaleAdult+Trafficked
BYMaleAdultTrafficked
UZMaleAdultTrafficked
IDMaleAdultTrafficked
BYMaleAdult+Trafficked
AFMaleYouthTrafficked
MXUnknownUnknownTrafficked
IDFemaleAdult-Trafficked
SYFemaleAdultTrafficked
QAFemaleAdultTrafficked
SAFemaleAdultTrafficked
SGFemaleAdultTrafficked
OMFemaleAdultTrafficked
TWFemaleAdultTrafficked
BHFemaleAdultTrafficked
AEFemaleAdult+Trafficked
IDFemaleYouthTrafficked
UAMaleAdult-Trafficked
TTMaleAdultTrafficked
ZAMaleAdultTrafficked
MYMaleAdultTrafficked
BYMaleYouthTrafficked
EGMaleYouthTrafficked
CNUnknownUnknownTrafficked
LBFemaleAdultTrafficked
BYFemaleYouthTrafficked
IDMaleAdult-Trafficked
DKMaleAdultTrafficked
IDMaleAdult+Trafficked
SAMaleYouthTrafficked
USFemaleAdult-Trafficked
USFemaleAdultTrafficked
USFemaleYouthTrafficked
USFemaleUnknownTrafficked
ZZFemaleUnknownTrafficked
USMaleUnknownTrafficked
USUnknownUnknownTrafficked
JPFemaleUnknownTrafficked
KWFemaleUnknownTrafficked
PHFemaleUnknownTrafficked
QAFemaleUnknownTrafficked
SAFemaleUnknownTrafficked
AEFemaleUnknownTrafficked
MYFemaleUnknownTrafficked
LBFemaleUnknownTrafficked
PHMaleAdult-Trafficked
THMaleAdultTrafficked
MUMaleAdultTrafficked
PHMaleUnknownTrafficked
MYMaleUnknownTrafficked
QAMaleUnknownTrafficked
USFemaleAdult+Trafficked
USMaleYouthTrafficked
ZZUnknownUnknownTrafficked
KHFemaleYouthTrafficked
CNFemaleAdult-Trafficked
CNFemaleAdultTrafficked
VNFemaleAdultTrafficked
THFemaleAdultTrafficked
HKFemaleAdultTrafficked
KHFemaleAdultTrafficked
CNFemaleYouthTrafficked
THMaleAdult-Trafficked
KHMaleYouthTrafficked
USMaleAdult-Trafficked
USMaleAdultTrafficked
USUnknownYouthTrafficked
KHFemaleAdult-Trafficked
MGFemaleAdultTrafficked
SLFemaleAdultTrafficked
THFemaleUnknownTrafficked
KHFemaleUnknownTrafficked
KHMaleAdult-Trafficked
KHMaleAdultTrafficked
KHMaleUnknownTrafficked

In [10]:
traffickingCounts.head()

                  UnknownUnknownUnknownTrafficked  \
citizenship Year
AF          2013                                0
            2014                                0
            2015                                0
AL          2005                                0
BD          2015                                0

                  UnknownFemaleAdult-Trafficked  Y1FemaleAdult-Trafficked  \
citizenship Year
AF          2013                              0                         0
            2014                              0                         0
            2015                              0                         0
AL          2005                              0                         0
BD          2015                              0                         0

                  BAFemaleAdult-Trafficked  MKFemaleAdult-Trafficked  \
citizenship Year
AF          2013                         0                         0
            2014                         0                         0
            2015                         0                         0
AL          2005                         0                         0
BD          2015                         0                         0

                  UnknownFemaleAdultTrafficked  Y1FemaleAdultTrafficked  \
citizenship Year
AF          2013                             0                        0
            2014                             0                        0
            2015                             0                        0
AL          2005                             0                        0
BD          2015                             0                        0

                  BAFemaleAdultTrafficked  MKFemaleAdultTrafficked  \
citizenship Year
AF          2013                        0                        0
            2014                        0                        0
            2015                        0                        0
AL          2005                        0                        0
BD          2015                        0                        0

                  MKFemaleYouthTrafficked           ...             \
citizenship Year                                    ...
AF          2013                        0           ...
            2014                        0           ...
            2015                        0           ...
AL          2005                        0           ...
BD          2015                        0           ...

                  USMaleAdultTrafficked  USUnknownYouthTrafficked  \
citizenship Year
AF          2013                      0                         0
            2014                      0                         0
            2015                      0                         0
AL          2005                      0                         0
BD          2015                      0                         0

                  KHFemaleAdult-Trafficked  MGFemaleAdultTrafficked  \
citizenship Year
AF          2013                         0                        0
            2014                         0                        0
            2015                         0                        0
AL          2005                         0                        0
BD          2015                         0                        0

                  SLFemaleAdultTrafficked  THFemaleUnknownTrafficked  \
citizenship Year
AF          2013                        0                          0
            2014                        0                          0
            2015                        0                          0
AL          2005                        0                          0
BD          2015                        0                          0

                  KHFemaleUnknownTrafficked  KHMaleAdult-Trafficked  \
citizenship Year
AF          2013                          0                       0
            2014                          0                       0
            2015                          0                       0
AL          2005                          0                       0
BD          2015                          0                       0

                  KHMaleAdultTrafficked  KHMaleUnknownTrafficked
citizenship Year
AF          2013                      0                        0
            2014                      0                        0
            2015                      0                        0
AL          2005                      0                        0
BD          2015                      0                        0

[5 rows x 168 columns]

In [51]:
Total = traffickingCounts.T.sum().reset_index().rename(columns={0:"TotalTrafficked"})\
.set_index(['citizenship', 'Year'])

TotalFemale = traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('Female')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalFemaleTrafficked"})\
.set_index(['citizenship', 'Year'])

TotalMale = traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('Male')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalMaleTrafficked"})\
.set_index(['citizenship', 'Year'])

TotalChild =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('Child')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalChildTrafficked"})\
.set_index(['citizenship', 'Year'])


TotalAdultMinus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('Adult-')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalAdult-Trafficked"})\
.set_index(['citizenship', 'Year'])

TotalAdult =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('AdultTraf')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalAdultTrafficked"})\
.set_index(['citizenship', 'Year'])

TotalAdultPlus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('Adult+')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalAdult+Trafficked"})\
.set_index(['citizenship', 'Year'])


TotalMaleChild =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('MaleChild')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalMaleChildTrafficked"})\
.set_index(['citizenship', 'Year'])


TotalMaleAdultMinus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('MaleAdult-')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalMaleAdult-Trafficked"})\
.set_index(['citizenship', 'Year'])

TotalMaleAdult =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('MaleAdultTraf')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalMaleAdultTrafficked"})\
.set_index(['citizenship', 'Year'])

TotalMaleAdultPlus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('MaleAdult+')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalMaleAdult+Trafficked"})\
.set_index(['citizenship', 'Year'])

TotalFemaleChild =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('MaleChild')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalFemaleChildTrafficked"})\
.set_index(['citizenship', 'Year'])


TotalFemaleAdultMinus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('FemaleAdult-')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalFemaleAdult-Trafficked"})\
.set_index(['citizenship', 'Year'])

TotalFemaleAdult =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('FemaleAdultTraf')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalFemaleAdultTrafficked"})\
.set_index(['citizenship', 'Year'])

TotalFemaleAdultPlus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
                                            .columns.to_series().str.contains('FemaleAdult+')]] \
                                            .T.sum().reset_index().rename(columns={0:"TotalFemaleAdult+Trafficked"})\
.set_index(['citizenship', 'Year'])


FinalTotals = pandas.concat([Total, TotalChild, TotalAdult,
                 TotalAdultMinus, TotalAdultPlus, TotalFemale, TotalMale,
                 TotalMaleChild, TotalMaleAdultMinus, TotalMaleAdult, TotalMaleAdultPlus,
                TotalFemaleChild,TotalFemaleAdultMinus, TotalFemaleAdult, TotalFemaleAdultPlus],axis=1, join='outer')

In [349]:
FinalTrafficking = pandas.concat([FinalTotals, traffickingCounts], axis=1, join='outer')

FinalTrafficking = FinalTrafficking.reset_index().rename(columns={'citizenship': 'code'})
FinalTrafficking

,code,Year,TotalTrafficked,TotalChildTrafficked,TotalAdultTrafficked,TotalAdult-Trafficked,TotalAdult+Trafficked,TotalFemaleTrafficked,TotalMaleTrafficked,TotalMaleChildTrafficked,...,USMaleAdultTrafficked,USUnknownYouthTrafficked,KHFemaleAdult-Trafficked,MGFemaleAdultTrafficked,SLFemaleAdultTrafficked,THFemaleUnknownTrafficked,KHFemaleUnknownTrafficked,KHMaleAdult-Trafficked,KHMaleAdultTrafficked,KHMaleUnknownTrafficked
0,AF,2013,37.0,0.0,0,0,0,0,37,0.0,...,0,0,0,0,0,0,0,0,0,0
1,AF,2014,188.0,0.0,0,0,0,16,172,0.0,...,0,0,0,0,0,0,0,0,0,0
2,AF,2015,14.0,0.0,0,0,0,0,14,0.0,...,0,0,0,0,0,0,0,0,0,0
3,AL,2005,45.0,0.0,11,23,34,45,0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,BD,2015,11.0,0.0,11,0,11,0,11,0.0,...,0,0,0,0,0,0,0,0,0,0
5,BF,2010,33.0,0.0,0,14,14,0,33,0.0,...,0,0,0,0,0,0,0,0,0,0
6,BG,2005,116.0,0.0,35,66,101,116,0,0.0,...,0,0,0,0,0,0,0,0,0,0
7,BG,2007,226.0,0.0,153,46,199,226,0,0.0,...,0,0,0,0,0,0,0,0,0,0
8,BO,2012,18.0,0.0,0,0,0,18,0,0.0,...,0,0,0,0,0,0,0,0,0,0
9,BY,2004,59.0,0.0,24,21,45,59,0,0.0,...,0,0,0,0,0,0,0,0,0,0
10,BY,2005,292.0,0.0,178,67,258,183,109,0.0,...,0,0,0,0,0,0,0,0,0,0
11,BY,2006,257.0,0.0,199,39,257,106,151,0.0,...,0,0,0,0,0,0,0,0,0,0
12,BY,2007,26.0,0.0,11,15,26,26,0,0.0,...,0,0,0,0,0,0,0,0,0,0
13,BY,2008,11.0,0.0,11,0,11,11,0,0.0,...,0,0,0,0,0,0,0,0,0,0
14,BY,2010,14.0,0.0,14,0,14,14,0,0.0,...,0,0,0,0,0,0,0,0,0,0
15,BY,2011,88.0,0.0,71,0,71,35,53,0.0,...,0,0,0,0,0,0,0,0,0,0
16,BY,2012,161.0,0.0,121,11,132,85,76,0.0,...,0,0,0,0,0,0,0,0,0,0
17,BY,2013,301.0,0.0,244,0,301,51,250,0.0,...,0,0,0,0,0,0,0,0,0,0
18,BY,2014,58.0,0.0,31,0,44,0,58,0.0,...,0,0,0,0,0,0,0,0,0,0
19,BY,2015,106.0,0.0,59,0,84,22,84,0.0,...,0,0,0,0,0,0,0,0,0,0
20,BY,2016,114.0,0.0,81,0,114,0,114,0.0,...,0,0,0,0,0,0,0,0,0,0
21,BY,2017,30.0,0.0,30,0,30,0,30,0.0,...,0,0,0,0,0,0,0,0,0,0
22,CD,2007,53.0,0.0,0,0,0,25,28,0.0,...,0,0,0,0,0,0,0,0,0,0
23,CI,2007,31.0,0.0,0,0,0,0,31,0.0,...,0,0,0,0,0,0,0,0,0,0
24,CN,2015,27.0,0.0,0,0,0,27,0,0.0,...,0,0,0,0,0,0,0,0,0,0
25,CN,2016,52.0,0.0,0,0,0,52,0,0.0,...,0,0,0,0,0,0,0,0,0,0
26,CN,2017,36.0,0.0,11,0,11,36,0,0.0,...,0,0,0,0,0,0,0,0,0,0
27,CO,2002,74.0,0.0,32,11,43,74,0,0.0,...,0,0,0,0,0,0,0,0,0,0
28,CO,2003,37.0,0.0,0,0,0,22,15,0.0,...,0,0,0,0,0,0,0,0,0,0
29,CO,2010,13.0,0.0,13,0,13,13,0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,UA,2012,859.0,0.0,704,26,808,389,470,0.0,...,0,0,0,0,0,0,0,0,0,0
128,UA,2013,638.0,0.0,488,14,638,266,372,0.0,...,0,0,0,0,0,0,0,0,0,0
129,UA,2014,735.0,0.0,597,14,735,300,435,0.0,...,0,0,0,0,0,0,0,0,0,0
130,UA,2015,422.0,0.0,314,0,406,199,223,0.0,...,0,0,0,0,0,0,0,0,0,0
131,UA,2016,794.0,0.0,673,16,794,273,521,0.0,...,0,0,0,0,0,0,0,0,0,0
132,UA,2017,1174.0,0.0,951,24,1160,455,719,0.0,...,0,0,0,0,0,0,0,0,0,0
133,UA,2018,240.0,0.0,190,0,240,82,158,0.0,...,0,0,0,0,0,0,0,0,0,0
134,UG,2014,70.0,0.0,0,0,0,44,26,0.0,...,0,0,0,0,0,0,0,0,0,0
135,US,2015,1261.0,0.0,243,133,376,1261,0,0.0,...,0,0,0,0,0,0,0,0,0,0
136,US,2016,1529.0,0.0,631,218,863,1518,11,0.0,...,0,0,0,0,0,0,0,0,0,0
137,US,2017,1369.0,0.0,600,204,804,1369,0,0.0,...,0,0,0,0,0,0,0,0,0,0
138,UZ,2005,78.0,0.0,67,11,78,78,0,0.0,...,0,0,0,0,0,0,0,0,0,0
139,UZ,2011,31.0,0.0,31,0,31,0,31,0.0,...,0,0,0,0,0,0,0,0,0,0
140,UZ,2013,115.0,0.0,87,28,115,101,14,0.0,...,0,0,0,0,0,0,0,0,0,0
141,UZ,2015,11.0,0.0,11,0,11,0,11,0.0,...,0,0,0,0,0,0,0,0,0,0
142,UZ,2017,26.0,0.0,26,0,26,0,26,0.0,...,0,0,0,0,0,0,0,0,0,0
143,Unknown,2002,13.0,0.0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
144,Unknown,2009,41.0,0.0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
145,Unknown,2013,29.0,0.0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
146,Unknown,2014,13.0,0.0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
147,Unknown,2015,14.0,0.0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
148,Unknown,2016,25.0,0.0,0,0,0,25,0,0.0,...,0,0,0,0,0,0,0,0,0,0
149,Unknown,2017,196.0,0.0,0,0,0,119,77,0.0,...,0,0,0,0,0,0,0,0,0,0
150,Unknown,2018,11.0,0.0,0,0,0,11,0,0.0,...,0,0,0,0,0,11,0,0,0,0
151,VN,2016,15.0,0.0,15,0,15,0,15,0.0,...,0,0,0,0,0,0,0,0,0,0
152,VN,2017,139.0,0.0,128,0,128,139,0,0.0,...,0,0,0,0,0,0,0,0,0,0
153,VN,2018,31.0,0.0,0,0,0,31,0,0.0,...,0,0,0,0,0,0,31,0,0,0
154,ZZ,2015,2595.0,0.0,240,148,388,2434,95,0.0,...,0,0,0,0,0,0,0,0,0,0
155,ZZ,2016,3840.0,0.0,652,378,1058,3550,190,0.0,...,0,0,0,0,0,0,0,0,0,0
156,ZZ,2017,5883.0,0.0,915,445,1400,5263,345,0.0,...,0,14,0,0,0,0,0,0,0,0

In [316]:
migrationA = pandas.read_csv('MigrationCountsAge-Gender.csv',error_bad_lines=False)
migrationA = migrationA.rename(columns={'Major area, region, country or area of destination': 'Destination'})

migrationA['Origin'] = 'WORLD'
migrationA = migrationA.set_index('Origin').reset_index()

# migrationA = migrationA.set_index(['Origin', 'Year', 'Destination'])
migrationA.tail(2050)
# migrationA.dtypes

,Origin,Destination,Year,Total,TotalYouth,TotalAdult,TotalElder,TotalMale,MaleYouth,MaleAdult,MaleElder,TotalFemale,FemaleYouth,FemaleAdult,FemaleElder
0,WORLD,Burundi,1990,333110,86938,230870,15302,163267,41491,114075,7701,169843,45447,116795,7601
1,WORLD,Comoros,1990,14079,3656,9973,450,6717,1561,4925,231,7362,2095,5048,219
2,WORLD,Djibouti,1990,122221,41767,77766,2688,64242,22913,39825,1504,57979,18854,37941,1184
3,WORLD,Eritrea,1990,11848,3311,8197,340,6228,1769,4305,154,5620,1542,3892,186
4,WORLD,Ethiopia,1990,1155390,396648,711765,46977,607284,211289,373118,22877,548106,185359,338647,24100
5,WORLD,Kenya,1990,297292,109787,172741,14764,160852,58215,94389,8248,136440,51572,78352,6516
6,WORLD,Madagascar,1990,23917,4910,15716,3291,13348,2103,9088,2157,10569,2807,6628,1134
7,WORLD,Malawi,1990,1127724,569896,525173,32655,546520,266422,264633,15465,581204,303474,260540,17190
8,WORLD,Mauritius,1990,3613,1182,2103,328,1763,579,1025,159,1850,603,1078,169
9,WORLD,Mayotte,1990,15229,4575,10354,300,8780,2311,6289,180,6449,2264,4065,120
10,WORLD,Mozambique,1990,122332,55885,63671,2776,66060,29090,35463,1507,56272,26795,28208,1269
11,WORLD,Réunion,1990,57210,19488,35704,2018,30724,9995,19600,1129,26486,9493,16104,889
12,WORLD,Rwanda,1990,159869,40818,108659,10392,80690,19547,57558,3585,79179,21271,51101,6807
13,WORLD,Seychelles,1990,3721,685,2857,179,2204,358,1761,85,1517,327,1096,94
14,WORLD,Somalia,1990,478294,238158,234399,5737,244201,111489,129580,3132,234093,126669,104819,2605
15,WORLD,South Sudan,1990,0,0,0,0,0,0,0,0,0,0,0,0
16,WORLD,Uganda,1990,558307,179337,347582,31388,290084,89963,181373,18748,268223,89374,166209,12640
17,WORLD,United Republic of Tanzania,1990,574025,187492,351748,34785,283390,90520,173885,18985,290635,96972,177863,15800
18,WORLD,Zambia,1990,279029,95900,171830,11299,142807,48007,88578,6222,136222,47893,83252,5077
19,WORLD,Zimbabwe,1990,626821,161731,444142,20948,352028,78684,262992,10352,274793,83047,181150,10596
20,WORLD,Middle Africa,1990,1460530,576982,835208,48340,744494,292423,426366,25705,716036,284559,408842,22635
21,WORLD,Angola,1990,33517,11666,20545,1306,18142,5523,11879,740,15375,6143,8666,566
22,WORLD,Cameroon,1990,265344,94132,165601,5611,145527,50769,91254,3504,119817,43363,74347,2107
23,WORLD,Central African Republic,1990,67234,28605,36515,2114,35686,14611,19936,1139,31548,13994,16579,975
24,WORLD,Chad,1990,74342,29398,41364,3580,40133,15192,22602,2339,34209,14206,18762,1241
25,WORLD,Congo,1990,129597,37215,87320,5062,64418,17269,44404,2745,65179,19946,42916,2317
26,WORLD,Democratic Republic of the Congo,1990,754194,327138,400152,26904,363117,163871,186120,13126,391077,163267,214032,13778
27,WORLD,Equatorial Guinea,1990,2740,757,1827,156,1465,312,1064,89,1275,445,763,67
28,WORLD,Gabon,1990,127980,46536,78129,3315,73053,24207,46963,1883,54927,22329,31166,1432
29,WORLD,Sao Tome and Principe,1990,5582,1535,3755,292,2953,669,2144,140,2629,866,1611,152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1847,WORLD,Saint Pierre and Miquelon,2017,990,236,682,72,519,124,365,30,471,112,317,42
1848,WORLD,United States of America,2017,49776970,3518317,38471339,7787314,24191609,1778745,19136148,3276716,25585361,1739572,19335191,4510598
1849,WORLD,OCEANIA,2017,8410933,878413,5912349,1620171,4122782,449565,2889919,783298,4288151,428848,3022430,836873
1850,WORLD,Australia/New Zealand,2017,8102983,820139,5691250,1591594,3957706,419828,2770234,767644,4145277,400311,2921016,823950
1851,WORLD,Australia,2017,7035560,681193,4942838,1411529,3441530,348502,2411999,681029,3594030,332691,2530839,730500
1852,WORLD,New Zealand,2017,1067423,138946,748412,180065,516176,71326,358235,86615,551247,67620,390177,93450
1853,WORLD,Melanesia,2017,118078,23673,80354,14051,66642,12597,46091,7954,51436,11076,34263,6097
1854,WORLD,Fiji,2017,13911,3016,9570,1325,7508,1663,5104,741,6403,1353,4466,584
1855,WORLD,New Caledonia,2017,66001,8096,47404,10501,35543,4239,25493,5811,30458,3857,21911,4690
1856,WORLD,Papua New Guinea,2017,32389,11188,19420,1781,20558,6055,13343,1160,11831,5133,6077,621
1857,WORLD,Solomon Islands,2017,2532,526,1778,228,1421,270,1027,124,1111,256,751,104
1858,WORLD,Vanuatu,2017,3245,847,2182,216,1612,370,1124,118,1633,477,1058,98
1859,WORLD,Micronesia,2017,117601,19940,89262,8399,59648,9751,45757,4140,57953,10189,43505,4259
1860,WORLD,Guam,2017,78027,12737,58841,6449,40246,6547,30495,3204,37781,6190,28346,3245
1861,WORLD,Kiribati,2017,3022,753,2123,146,1594,390,1129,75,1428,363,994,71
1862,WORLD,Marshall Islands,2017,3292,849,2281,162,2016,479,1441,96,1276,370,840,66
1863,WORLD,Micronesia (Fed. States of),2017,2785,638,1946,201,1489,286,1079,124,1296,352,867,77
1864,WORLD,Nauru,2017,3710,802,2624,284,2317,501,1633,183,1393,301,991,101
1865,WORLD,Northern Mariana Islands,2017,21777,3625,17213,939,9155,1274,7555,326,12622,2351,9658,613
1866,WORLD,Palau,2017,4988,536,4234,218,2831,274,2425,132,2157,262,1809,86
1867,WORLD,Polynesia,2017,72271,14661,51483,6127,38786,7389,27837,3560,33485,7272,23646,2567
1868,WORLD,American Samoa,2017,23561,3549,18037,1975,12023,1793,9222,1008,11538,1756,8815,967
1869,WORLD,Cook Islands,2017,4213,1412,2586,215,2109,698,1333,78,2104,714,1253,137
1870,WORLD,French Polynesia,2017,30687,4792,22692,3203,17495,2440,12913,2142,13192,2352,9779,1061
1871,WORLD,Niue,2017,553,252,284,17,300,123,169,8,253,129,115,9
1872,WORLD,Samoa,2017,4879,2188,2404,287,2444,1083,1217,144,2435,1105,1187,143
1873,WORLD,Tokelau,2017,504,250,221,33,242,115,119,8,262,135,102,25
1874,WORLD,Tonga,2017,4952,1529,3186,237,2691,784,1792,115,2261,745,1394,122
1875,WORLD,Tuvalu,2017,143,32,77,34,79,22,46,11,64,10,31,23
1876,WORLD,Wallis and Futuna Islands,2017,2779,657,1996,126,1403,331,1026,46,1376,326,970,80

In [207]:
migrationB.dtypes

Year              int64
Destination      object
Origin           object
TotalMigrants    object
dtype: object

In [318]:
migrationB = pandas.read_csv('NumberofPeopleMigrated_PerCountries_PerYear.csv')
migrationB = migrationB.rename(columns={'Years': 'Year', '2': "Origin", 'value':'TotalMigrants'})
migrationB = migrationB.drop('Unnamed: 0', axis=1)
MigrantNums = migrationB['TotalMigrants'].replace("..", 0)
# migrationB = migrationB.set_index(['Origin', 'Year'])


migrationB['TotalMigrants'] = migrationB['TotalMigrants'].apply(lambda x: x.replace('..','0'))
migrationB['TotalMigrants'] = migrationB['TotalMigrants'].apply(lambda x: pandas.to_numeric(x.replace(',','')))

In [319]:
migrationB2 =  pandas.pivot_table(migrationB, index=['Origin', 'Year'], columns='Countries of Destination', values='TotalMigrants')
migrationB2 =  migrationB2.reset_index()
migrationB2.head()

Countries of Destination,Origin,Year,AFRICA,ASIA,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,...,Viet Nam,WORLD,Wallis and Futuna Islands,Western Africa,Western Asia,Western Europe,Western Sahara,Yemen,Zambia,Zimbabwe
0,Afghanistan,1990,1037,6604107,0,0,0,0,0,0,...,0,6724681,0,0,180765,53039,0,0,0,0
1,Afghanistan,1995,737,3453717,0,0,0,0,0,0,...,0,3625571,0,0,187343,77161,0,0,0,0
2,Afghanistan,2000,478,4317635,0,0,0,0,0,0,...,0,4541159,0,0,192198,101775,0,0,0,0
3,Afghanistan,2005,534,3522203,0,0,0,0,0,0,...,0,3826255,0,0,234996,122779,0,0,0,0
4,Afghanistan,2010,606,4606872,0,0,0,0,0,0,...,0,4989209,0,0,306777,129501,0,0,0,0

In [333]:
FinalMigration = migrationA.join(migrationB2, lsuffix='', rsuffix='_r').drop(['Origin_r', 'Year_r'], axis=1)
FinalMigration

,Origin,Destination,Year,Total,TotalYouth,TotalAdult,TotalElder,TotalMale,MaleYouth,MaleAdult,...,Viet Nam,WORLD,Wallis and Futuna Islands,Western Africa,Western Asia,Western Europe,Western Sahara,Yemen,Zambia,Zimbabwe
0,WORLD,Burundi,1990,333110,86938,230870,15302,163267,41491,114075,...,0.0,6724681.0,0.0,0.0,180765.0,53039.0,0.0,0.0,0.0,0.0
1,WORLD,Comoros,1990,14079,3656,9973,450,6717,1561,4925,...,0.0,3625571.0,0.0,0.0,187343.0,77161.0,0.0,0.0,0.0,0.0
2,WORLD,Djibouti,1990,122221,41767,77766,2688,64242,22913,39825,...,0.0,4541159.0,0.0,0.0,192198.0,101775.0,0.0,0.0,0.0,0.0
3,WORLD,Eritrea,1990,11848,3311,8197,340,6228,1769,4305,...,0.0,3826255.0,0.0,0.0,234996.0,122779.0,0.0,0.0,0.0,0.0
4,WORLD,Ethiopia,1990,1155390,396648,711765,46977,607284,211289,373118,...,0.0,4989209.0,0.0,0.0,306777.0,129501.0,0.0,0.0,0.0,0.0
5,WORLD,Kenya,1990,297292,109787,172741,14764,160852,58215,94389,...,0.0,4855376.0,0.0,3.0,416191.0,138201.0,0.0,0.0,0.0,0.0
6,WORLD,Madagascar,1990,23917,4910,15716,3291,13348,2103,9088,...,0.0,4826464.0,0.0,2.0,469791.0,166425.0,0.0,0.0,0.0,0.0
7,WORLD,Malawi,1990,1127724,569896,525173,32655,546520,266422,264633,...,0.0,179490.0,0.0,0.0,870.0,13502.0,0.0,0.0,0.0,0.0
8,WORLD,Mauritius,1990,3613,1182,2103,328,1763,579,1025,...,0.0,500353.0,0.0,0.0,2037.0,16971.0,0.0,0.0,0.0,0.0
9,WORLD,Mayotte,1990,15229,4575,10354,300,8780,2311,6289,...,0.0,823668.0,0.0,0.0,3223.0,20418.0,0.0,0.0,0.0,0.0
10,WORLD,Mozambique,1990,122332,55885,63671,2776,66060,29090,35463,...,0.0,965066.0,0.0,0.0,3375.0,25808.0,0.0,0.0,0.0,0.0
11,WORLD,Réunion,1990,57210,19488,35704,2018,30724,9995,19600,...,0.0,1129071.0,0.0,0.0,3582.0,30255.0,0.0,0.0,0.0,0.0
12,WORLD,Rwanda,1990,159869,40818,108659,10392,80690,19547,57558,...,0.0,1137917.0,0.0,11.0,3636.0,33014.0,0.0,0.0,0.0,0.0
13,WORLD,Seychelles,1990,3721,685,2857,179,2204,358,1761,...,0.0,1148144.0,0.0,10.0,4235.0,36795.0,0.0,0.0,0.0,0.0
14,WORLD,Somalia,1990,478294,238158,234399,5737,244201,111489,129580,...,0.0,906030.0,0.0,5594.0,19931.0,815727.0,41.0,0.0,0.0,0.0
15,WORLD,South Sudan,1990,0,0,0,0,0,0,0,...,0.0,965162.0,0.0,6049.0,26225.0,845994.0,45.0,0.0,0.0,0.0
16,WORLD,Uganda,1990,558307,179337,347582,31388,290084,89963,181373,...,0.0,1025039.0,0.0,5876.0,31110.0,876097.0,50.0,0.0,0.0,0.0
17,WORLD,United Republic of Tanzania,1990,574025,187492,351748,34785,283390,90520,173885,...,0.0,1588723.0,0.0,7854.0,38214.0,1374748.0,59.0,0.0,0.0,0.0
18,WORLD,Zambia,1990,279029,95900,171830,11299,142807,48007,88578,...,0.0,1630181.0,0.0,10023.0,45761.0,1363653.0,68.0,0.0,0.0,0.0
19,WORLD,Zimbabwe,1990,626821,161731,444142,20948,352028,78684,262992,...,0.0,1785555.0,0.0,17506.0,46716.0,1499864.0,78.0,0.0,0.0,0.0
20,WORLD,Middle Africa,1990,1460530,576982,835208,48340,744494,292423,426366,...,0.0,1792712.0,0.0,17655.0,45718.0,1501581.0,81.0,0.0,0.0,0.0
21,WORLD,Angola,1990,33517,11666,20545,1306,18142,5523,11879,...,0.0,2041.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
22,WORLD,Cameroon,1990,265344,94132,165601,5611,145527,50769,91254,...,0.0,2638.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
23,WORLD,Central African Republic,1990,67234,28605,36515,2114,35686,14611,19936,...,0.0,3186.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
24,WORLD,Chad,1990,74342,29398,41364,3580,40133,15192,22602,...,0.0,2678.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0
25,WORLD,Congo,1990,129597,37215,87320,5062,64418,17269,44404,...,0.0,1975.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
26,WORLD,Democratic Republic of the Congo,1990,754194,327138,400152,26904,363117,163871,186120,...,0.0,2035.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
27,WORLD,Equatorial Guinea,1990,2740,757,1827,156,1465,312,1064,...,0.0,2037.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
28,WORLD,Gabon,1990,127980,46536,78129,3315,73053,24207,46963,...,0.0,3792.0,0.0,0.0,0.0,1254.0,0.0,0.0,0.0,0.0
29,WORLD,Sao Tome and Principe,1990,5582,1535,3755,292,2953,669,2144,...,0.0,4193.0,0.0,0.0,0.0,1300.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1847,WORLD,Saint Pierre and Miquelon,2017,990,236,682,72,519,124,365,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1848,WORLD,United States of America,2017,49776970,3518317,38471339,7787314,24191609,1778745,19136148,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1849,WORLD,OCEANIA,2017,8410933,878413,5912349,1620171,4122782,449565,2889919,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1850,WORLD,Australia/New Zealand,2017,8102983,820139,5691250,1591594,3957706,419828,2770234,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1851,WORLD,Australia,2017,7035560,681193,4942838,1411529,3441530,348502,2411999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1852,WORLD,New Zealand,2017,1067423,138946,748412,180065,516176,71326,358235,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1853,WORLD,Melanesia,2017,118078,23673,80354,14051,66642,12597,46091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1854,WORLD,Fiji,2017,13911,3016,9570,1325,7508,1663,5104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1855,WORLD,New Caledonia,2017,66001,8096,47404,10501,35543,4239,25493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1856,WORLD,Papua New Guinea,2017,32389,11188,19420,1781,20558,6055,13343,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1857,WORLD,Solomon Islands,2017,2532,526,1778,228,1421,270,1027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1858,WORLD,Vanuatu,2017,3245,847,2182,216,1612,370,1124,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1859,WORLD,Micronesia,2017,117601,19940,89262,8399,59648,9751,45757,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860,WORLD,Guam,2017,78027,12737,58841,6449,40246,6547,30495,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1861,WORLD,Kiribati,2017,3022,753,2123,146,1594,390,1129,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1862,WORLD,Marshall Islands,2017,3292,849,2281,162,2016,479,1441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1863,WORLD,Micronesia (Fed. States of),2017,2785,638,1946,201,1489,286,1079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1864,WORLD,Nauru,2017,3710,802,2624,284,2317,501,1633,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1865,WORLD,Northern Mariana Islands,2017,21777,3625,17213,939,9155,1274,7555,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1866,WORLD,Palau,2017,4988,536,4234,218,2831,274,2425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1867,WORLD,Polynesia,2017,72271,14661,51483,6127,38786,7389,27837,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1868,WORLD,American Samoa,2017,23561,3549,18037,1975,12023,1793,9222,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1869,WORLD,Cook Islands,2017,4213,1412,2586,215,2109,698,1333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1870,WORLD,French Polynesia,2017,30687,4792,22692,3203,17495,2440,12913,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1871,WORLD,Niue,2017,553,252,284,17,300,123,169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1872,WORLD,Samoa,2017,4879,2188,2404,287,2444,1083,1217,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1873,WORLD,Tokelau,2017,504,250,221,33,242,115,119,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1874,WORLD,Tonga,2017,4952,1529,3186,237,2691,784,1792,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1875,WORLD,Tuvalu,2017,143,32,77,34,79,22,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1876,WORLD,Wallis and Futuna Islands,2017,2779,657,1996,126,1403,331,1026,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [373]:
gdp = pandas.read_csv('Countries_GDP.csv')
gdp = pandas.DataFrame(gdp)
gdp = gdp.rename(columns={'Code':'code'})
gdp['code'] = gdp['code'].apply(str)
gdp = gdp.replace('..', -99)
gdp['GDP'] = gdp['GDP'].apply(float)
gdp = gdp.rename(columns={'GDP':'GDP(ppp)'})
# gdp.dtypes
gdp.head(5)

  Country Name code  Year     GDP(ppp)
0  Afghanistan   AF  1990   -99.000000
1  Afghanistan   AF  1995   -99.000000
2  Afghanistan   AF  2000   -99.000000
3  Afghanistan   AF  2005  1011.595524
4  Afghanistan   AF  2010  1581.600836

In [ ]:
 def colorPick(gdp_md_est):

# divided 190 countries into 7 equal categories
     
#     (190.0, 166.375, 142.75, 119.125, 95.5, 71.875, 48.25, 24.625, 1.0)
#  This is total gdp, in millijons

    if gdp_md_est > 500000:
        color = "CHARTREUSE"
    elif gdp_md_est > 200000:
        color = "PALEGREEN"
    elif gdp_md_est > 70000:
        color = "SKYBLUE"
    elif gdp_md_est > 35000:
        color = "PALEVIOLETRED"
    elif gdp_md_est > 15000:
        color = "SANDYBROWN"
    elif gdp_md_est > 7000:
        color = "ORANGERED"
    elif gdp_md_est > 2000:
        color = "RED"
    else:
        color = 'slategrey'

    return color

In [ ]:
for index,row in gdp.iterrows():
    gdp['color'] = gdp['GDP'].apply(colorPick)
gdp.head(5)
# gdp[gdp['code']=='BM']

In [367]:
gdp['code'].dtypes == FinalTrafficking['code'].dtypes and gdp['Year'].dtypes == FinalTrafficking['Year'].dtypes

True

In [384]:
TraffickedWithGdp = pandas.merge(FinalTrafficking,gdp, on=['code', 'Year'], how='left').sort_values('code')
TraffickedWithGdp.head(5)

,code,Year,TotalTrafficked,TotalChildTrafficked,TotalAdultTrafficked,TotalAdult-Trafficked,TotalAdult+Trafficked,TotalFemaleTrafficked,TotalMaleTrafficked,TotalMaleChildTrafficked,...,KHFemaleAdult-Trafficked,MGFemaleAdultTrafficked,SLFemaleAdultTrafficked,THFemaleUnknownTrafficked,KHFemaleUnknownTrafficked,KHMaleAdult-Trafficked,KHMaleAdultTrafficked,KHMaleUnknownTrafficked,Country Name,GDP(ppp)
0,AF,2013,37.0,0.0,0,0,0,0,37,0.0,...,0,0,0,0,0,0,0,0,NaN,NaN
1,AF,2014,188.0,0.0,0,0,0,16,172,0.0,...,0,0,0,0,0,0,0,0,NaN,NaN
2,AF,2015,14.0,0.0,0,0,0,0,14,0.0,...,0,0,0,0,0,0,0,0,Afghanistan,1926.357336
3,AL,2005,45.0,0.0,11,23,34,45,0,0.0,...,0,0,0,0,0,0,0,0,Albania,5942.884009
4,BD,2015,11.0,0.0,11,0,11,0,11,0.0,...,0,0,0,0,0,0,0,0,Bangladesh,3335.759791

In [381]:
traffickedGDPglobe = pandas.merge(Globem TraffickedWithGdp, on="code", how='left')
traffickedGDPglobe.tail(55)

,geometry.coordinates,geometry.type,properties.economy,properties.income_grp,code,properties.name,properties.sovereignt,properties.type,Year,TotalTrafficked,...,KHFemaleAdult-Trafficked,MGFemaleAdultTrafficked,SLFemaleAdultTrafficked,THFemaleUnknownTrafficked,KHFemaleUnknownTrafficked,KHMaleAdult-Trafficked,KHMaleAdultTrafficked,KHMaleUnknownTrafficked,Country Name,GDP(ppp)
1528,"[[[[-80.11510169199994, -2.997979424999855], [...",MultiPolygon,6. Developing region,3. Upper middle income,EC,Ecuador,Ecuador,Sovereign country,1990.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ecuador,4829.416723
1529,"[[[[-80.11510169199994, -2.997979424999855], [...",MultiPolygon,6. Developing region,3. Upper middle income,EC,Ecuador,Ecuador,Sovereign country,2015.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ecuador,11446.365140
1530,"[[[[-80.11510169199994, -2.997979424999855], [...",MultiPolygon,6. Developing region,3. Upper middle income,EC,Ecuador,Ecuador,Sovereign country,2017.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ecuador,11617.428850
1531,"[[[[-58.44102942599994, 6.904771226000108], [-...",MultiPolygon,6. Developing region,4. Lower middle income,GY,Guyana,Guyana,Sovereign country,2017.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guyana,8162.601540
1532,"[[[[-58.44102942599994, 6.904771226000108], [-...",MultiPolygon,6. Developing region,4. Lower middle income,GY,Guyana,Guyana,Sovereign country,2015.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guyana,7535.976471
1533,"[[[[-58.44102942599994, 6.904771226000108], [-...",MultiPolygon,6. Developing region,4. Lower middle income,GY,Guyana,Guyana,Sovereign country,2010.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guyana,5729.563121
1534,"[[[[-58.44102942599994, 6.904771226000108], [-...",MultiPolygon,6. Developing region,4. Lower middle income,GY,Guyana,Guyana,Sovereign country,1990.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guyana,1837.617440
1535,"[[[[-58.44102942599994, 6.904771226000108], [-...",MultiPolygon,6. Developing region,4. Lower middle income,GY,Guyana,Guyana,Sovereign country,1995.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guyana,2851.883235
1536,"[[[[-58.44102942599994, 6.904771226000108], [-...",MultiPolygon,6. Developing region,4. Lower middle income,GY,Guyana,Guyana,Sovereign country,2005.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guyana,4183.794746
1537,"[[[[-58.44102942599994, 6.904771226000108], [-...",MultiPolygon,6. Developing region,4. Lower middle income,GY,Guyana,Guyana,Sovereign country,2000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guyana,3584.189022
1538,"[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,CO,Colombia,Colombia,Sovereign country,2017.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,14552.008560
1539,"[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,CO,Colombia,Colombia,Sovereign country,2005.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,8248.355342
1540,"[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,CO,Colombia,Colombia,Sovereign country,2003.0,37.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1541,"[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,CO,Colombia,Colombia,Sovereign country,2002.0,74.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1542,"[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,CO,Colombia,Colombia,Sovereign country,2015.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,13827.672790
1543,"[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,CO,Colombia,Colombia,Sovereign country,2000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,6585.334138
1544,"[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,CO,Colombia,Colombia,Sovereign country,2010.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Colombia,10680.003010
1545,"[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,CO,Colombia,Colombia,Sovereign country,1990.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,4869.161847
1546,"[[[[-78.2048906179999, 2.687339382000118], [-7...",MultiPolygon,6. Developing region,3. Upper middle income,CO,Colombia,Colombia,Sovereign country,1995.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,6155.688861
1547,"[[[[-76.17565995399988, -14.28837484699987], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,PE,Peru,Peru,Sovereign country,2005.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peru,6762.772656
1548,"[[[[-76.17565995399988, -14.28837484699987], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,PE,Peru,Peru,Sovereign country,2010.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peru,9755.149148
1549,"[[[[-76.17565995399988, -14.28837484699987], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,PE,Peru,Peru,Sovereign country,2015.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peru,12533.491180
1550,"[[[[-76.17565995399988, -14.28837484699987], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,PE,Peru,Peru,Sovereign country,2017.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peru,13434.125600
1551,"[[[[-76.17565995399988, -14.28837484699987], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,PE,Peru,Peru,Sovereign country,2000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peru,5202.233095
1552,"[[[[-76.17565995399988, -14.28837484699987], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,PE,Peru,Peru,Sovereign country,1995.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peru,4539.560345
1553,"[[[[-76.17565995399988, -14.28837484699987], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,PE,Peru,Peru,Sovereign country,1990.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peru,3433.763634
1554,"[[[-56.90636673999998, -30.108548685999907], [...",Polygon,5. Emerging region: G20,3. Upper middle income,UY,Uruguay,Uruguay,Sovereign country,2010.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uruguay,16736.851040
1555,"[[[-56.90636673999998, -30.108548685999907], [...",Polygon,5. Emerging region: G20,3. Upper middle income,UY,Uruguay,Uruguay,Sovereign country,2005.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uruguay,11553.515510
1556,"[[[-56.90636673999998, -30.108548685999907], [...",Polygon,5. Emerging region: G20,3. Upper middle income,UY,Uruguay,Uruguay,Sovereign country,2000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uruguay,10204.905240
1557,"[[[-56.90636673999998, -30.108548685999907], [...",Polygon,5. Emerging region: G20,3. Upper middle income,UY,Uruguay,Uruguay,Sovereign country,1995.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uruguay,8392.743920
1558,"[[[-56.90636673999998, -30.108548685999907], [...",Polygon,5. Emerging region: G20,3. Upper middle income,UY,Uruguay,Uruguay,Sovereign country,1990.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uruguay,6360.382528
1559,"[[[-56.90636673999998, -30.108548685999907], [...",Polygon,5. Emerging region: G20,3. Upper middle income,UY,Uruguay,Uruguay,Sovereign country,2017.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uruguay,22562.461830
1560,"[[[-56.90636673999998, -30.108548685999907], [...",Polygon,5. Emerging region: G20,3. Upper middle income,UY,Uruguay,Uruguay,Sovereign country,2015.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uruguay,21117.801600
1561,"[[[-54.17096517463119, 5.348376149408466], [-5...",Polygon,6. Developing region,3. Upper middle income,SR,Suriname,Suriname,Sovereign country,1990.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Suriname,6815.595198
1562,"[[[-54.17096517463119, 5.348376149408466], [-5...",Polygon,6. Developing region,3. Upper middle income,SR,Suriname,Suriname,Sovereign country,2017.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Suriname,15114.296040
1563,"[[[-54.17096517463119, 5.348376149408466], [-5...",Polygon,6. Developing region,3. Upper middle income,SR,Suriname,Suriname,Sovereign country,2015.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Suriname,15724.639390
1564,"[[[-54.17096517463119, 5.348376149408466], [-5...",Polygon,6. Developing region,3. Upper middle income,SR,Suriname,Suriname,Sovereign country,2010.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Suriname,13924.390720
1565,"[[[-54.17096517463119, 5.348376149408466], [-5...",Polygon,6. Developing region,3. Upper middle income,SR,Suriname,Suriname,Sovereign country,2005.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Suriname,10834.592210
1566,"[[[-54.17096517463119, 5.348376149408466], [-5...",Polygon,6. Developing region,3. Upper middle income,SR,Suriname,Suriname,Sovereign country,2000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Suriname,7713.114214
1567,"[[[-54.17096517463119, 5.348376149408466], [-5...",Polygon,6. Developing region,3. Upper middle income,SR,Suriname,Suriname,Sovereign country,1995.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Suriname,7010.810181
1568,"[[[[-67.25609290299991, -55.82887135199992], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,CL,Chile,Chile,Sovereign country,2015.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chile,22785.818030
1569,"[[[[-67.25609290299991, -55.82887135199992], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,CL,Chile,Chile,Sovereign country,2010.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chile,18265.342530
1570,"[[[[-67.25609290299991, -55.82887135199992], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,CL,Chile,Chile,Sovereign country,2005.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chile,12774.731220
1571,"[[[[-67.25609290299991, -55.82887135199992], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,CL,Chile,Chile,Sovereign country,2000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chile,9571.978941
1572,"[[[[-67.25609290299991, -55.82887135199992], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,CL,Chile,Chile,Sovereign country,2017.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chile,24634.970210
1573,"[[[[-67.25609290299991, -55.82887135199992], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,CL,Chile,Chile,Sovereign country,1995.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chile,7366.063872
1574,"[[[[-67.25609290299991, -55.82887135199992], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,CL,Chile,Chile,Sovereign country,1990.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chile,4507.114744
1575,"[[[[-61.39027141599987, 8.580580853000143], [-...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,VE,Venezuela,Venezuela,Sovereign country,2010.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Venezuela, RB",16210.289960
1576,"[[[[-61.39027141599987, 8.580580853000143], [-...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,VE,Venezuela,Venezuela,Sovereign country,1990.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Venezuela, RB",9339.954430
1577,"[[[[-61.39027141599987, 8.580580853000143], [-...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,VE,Venezuela,Venezuela,Sovereign country,1995.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Venezuela, RB",11172.374170
1578,"[[[[-61.39027141599987, 8.580580853000143], [-...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,VE,Venezuela,Venezuela,Sovereign country,2000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Venezuela, RB",11424.204490
1579,"[[[[-61.39027141599987, 8.580580853000143], [-...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,VE,Venezuela,Venezuela,Sovereign country,2005.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Venezuela, RB",13309.697640
1580,"[[[[-61.39027141599987, 8.580580853000143], [-...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,VE,Venezuela,Venezuela,Sovereign country,2015.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Venezuela, RB",-99.000000
1581,"[[[[-61.39027141599987, 8.580580853000143], [-...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,VE,Venezuela,Venezuela,Sovereign country,2017.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Venezuela, RB",-99.000000
1582,"[[[[-157.9151098299999, -21.937676690999865], ...",MultiPolygon,6. Developing region,3. Upper middle income,CK,Cook Is.,New Zealand,Dependency,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
traffickedGDPmigrationGlobe = pandas.merge(traffickedGDPglobe, migration,
                                           left_on = 'Country Name', right_on = 'Origin', how="outer")
traffickedGDPmigrationGlobe