In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [3]:
df_gdp = pd.read_csv("Countries_GDP_Cleaned.csv",index_col=0)
df_gdp.head()

             Country Code  Years  GPD Values
Country Name
Afghanistan            AF   1990         0.0
Afghanistan            AF   1991         0.0
Afghanistan            AF   1992         0.0
Afghanistan            AF   1993         0.0
Afghanistan            AF   1994         0.0

In [4]:
df_mig_age_gen = pd.read_csv("MigrationCountsAge-Gender.csv", index_col=0)
df_mig_age_gen.head()

,Year,Total,TotalYouth,TotalAdult,TotalElder,TotalMale,MaleYouth,MaleAdult,MaleElder,TotalFemale,FemaleYouth,FemaleAdult,FemaleElder
"Major area, region, country or area of destination",,,,,,,,,,,,,
Burundi,1990,333110,86938,230870,15302,163267,41491,114075,7701,169843,45447,116795,7601
Comoros,1990,14079,3656,9973,450,6717,1561,4925,231,7362,2095,5048,219
Djibouti,1990,122221,41767,77766,2688,64242,22913,39825,1504,57979,18854,37941,1184
Eritrea,1990,11848,3311,8197,340,6228,1769,4305,154,5620,1542,3892,186
Ethiopia,1990,1155390,396648,711765,46977,607284,211289,373118,22877,548106,185359,338647,24100

In [5]:
df_mig_year = pd.read_csv("NumberPeopleMigratedFinal.csv", index_col=0)
df_mig_year.head()

,Years,Countries of Origin,Countries of Destination,Total Count
Country Code,,,,
AF,1990,Afghanistan,WORLD,6724681
AF,1990,Afghanistan,More developed regions,119338
AF,1990,Afghanistan,Less developed regions,6605343
AF,1990,Afghanistan,"Less developed regions, excluding least develo...",6605343
AF,1990,Afghanistan,High-income countries,269865

In [6]:
df_trafficking_counts = pd.read_csv("TraffickingCountsAge-Gender.csv", index_col=0)
df_trafficking_counts.head()

             Year CountryOfExploitation  gender ageBroad  Count
citizenship
CO           2002               Unknown  Female    Adult     32
CO           2002               Unknown  Female   Adult-     11
CO           2002               Unknown  Female  Unknown     31
MD           2002               Unknown  Female    Adult    396
MD           2002               Unknown  Female   Adult-    132

In [7]:
%pwd

'/Users/davidtabaka/Desktop/Project2_Neurath/DataSets'

In [8]:
engine = create_engine("sqlite:///db.sqlite")

In [16]:
df_trafficking_counts.to_sql("trafficking_counts",engine)

In [9]:
df_mig_year.to_sql("df_mig_year", engine)

ValueError: Table 'df_mig_year' already exists.

In [10]:
df_mig_age_gen.to_sql("mig_age_gen", engine)

In [11]:
df_gdp.to_sql("gdp", engine)

In [17]:
query = "select * from trafficking_counts"
df = pd.read_sql(query, engine)
df.head()

  citizenship  Year CountryOfExploitation  gender ageBroad  Count
0          CO  2002               Unknown  Female    Adult     32
1          CO  2002               Unknown  Female   Adult-     11
2          CO  2002               Unknown  Female  Unknown     31
3          MD  2002               Unknown  Female    Adult    396
4          MD  2002               Unknown  Female   Adult-    132

In [21]:
df.to_json(orient='records')

'[{"citizenship":"CO","Year":2002,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult","Count":32},{"citizenship":"CO","Year":2002,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult-","Count":11},{"citizenship":"CO","Year":2002,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Unknown","Count":31},{"citizenship":"MD","Year":2002,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult","Count":396},{"citizenship":"MD","Year":2002,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult-","Count":132},{"citizenship":"MD","Year":2002,"CountryOfExploitation":"Y1","gender":"Female","ageBroad":"Adult","Count":129},{"citizenship":"MD","Year":2002,"CountryOfExploitation":"Y1","gender":"Female","ageBroad":"Adult-","Count":27},{"citizenship":"RO","Year":2002,"CountryOfExploitation":"BA","gender":"Female","ageBroad":"Adult","Count":19},{"citizenship":"RO","Year":2002,"CountryOfExploitation":"BA","gender":"Female","ageBroad":"Adult-","Count":22},{"citizenship":"RO","Year":2002,"CountryOfExploitation":"MK","gender":"Female","ageBroad":"Adult","Count":50},{"citizenship":"RO","Year":2002,"CountryOfExploitation":"MK","gender":"Female","ageBroad":"Adult-","Count":46},{"citizenship":"RO","Year":2002,"CountryOfExploitation":"MK","gender":"Female","ageBroad":"Youth","Count":25},{"citizenship":"RO","Year":2002,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult","Count":47},{"citizenship":"RO","Year":2002,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult-","Count":26},{"citizenship":"RO","Year":2002,"CountryOfExploitation":"Y1","gender":"Female","ageBroad":"Adult","Count":13},{"citizenship":"RO","Year":2002,"CountryOfExploitation":"Y1","gender":"Female","ageBroad":"Adult-","Count":27},{"citizenship":"UA","Year":2002,"CountryOfExploitation":"MK","gender":"Female","ageBroad":"Adult","Count":54},{"citizenship":"UA","Year":2002,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult","Count":14},{"citizenship":"UA","Year":2002,"CountryOfExploitation":"Y1","gender":"Female","ageBroad":"Adult","Count":15},{"citizenship":"Unknown","Year":2002,"CountryOfExploitation":"Unknown","gender":"Unknown","ageBroad":"Unknown","Count":13},{"citizenship":"CO","Year":2003,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Unknown","Count":22},{"citizenship":"CO","Year":2003,"CountryOfExploitation":"Unknown","gender":"Male","ageBroad":"Unknown","Count":15},{"citizenship":"MD","Year":2003,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult","Count":166},{"citizenship":"MD","Year":2003,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult-","Count":71},{"citizenship":"RO","Year":2003,"CountryOfExploitation":"BA","gender":"Female","ageBroad":"Adult","Count":73},{"citizenship":"RO","Year":2003,"CountryOfExploitation":"MK","gender":"Female","ageBroad":"Adult-","Count":19},{"citizenship":"UA","Year":2003,"CountryOfExploitation":"BA","gender":"Female","ageBroad":"Adult","Count":13},{"citizenship":"BY","Year":2004,"CountryOfExploitation":"AE","gender":"Female","ageBroad":"Adult","Count":12},{"citizenship":"BY","Year":2004,"CountryOfExploitation":"CY","gender":"Female","ageBroad":"Adult","Count":12},{"citizenship":"BY","Year":2004,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult-","Count":21},{"citizenship":"BY","Year":2004,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Youth","Count":14},{"citizenship":"MD","Year":2004,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult","Count":75},{"citizenship":"MD","Year":2004,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult-","Count":58},{"citizenship":"MD","Year":2004,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Youth","Count":12},{"citizenship":"MD","Year":2004,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult","Count":15},{"citizenship":"MD","Year":2004,"CountryOfExploitation":"Unknown","gender":"Female","ageBroad":"Adult-","Count":14},{"citizenship":"UA","Year":2004,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult-","Count":17},{"citizenship":"AL","Year":2005,"CountryOfExploitation":"AL","gender":"Female","ageBroad":"Adult","Count":11},{"citizenship":"AL","Year":2005,"CountryOfExploitation":"AL","gender":"Female","ageBroad":"Adult-","Count":23},{"citizenship":"AL","Year":2005,"CountryOfExploitation":"AL","gender":"Female","ageBroad":"Youth","Count":11},{"citizenship":"BG","Year":2005,"CountryOfExploitation":"BG","gender":"Female","ageBroad":"Adult","Count":35},{"citizenship":"BG","Year":2005,"CountryOfExploitation":"BG","gender":"Female","ageBroad":"Adult-","Count":66},{"citizenship":"BG","Year":2005,"CountryOfExploitation":"BG","gender":"Female","ageBroad":"Youth","Count":15},{"citizenship":"BY","Year":2005,"CountryOfExploitation":"AE","gender":"Female","ageBroad":"Adult","Count":45},{"citizenship":"BY","Year":2005,"CountryOfExploitation":"AE","gender":"Female","ageBroad":"Adult-","Count":19},{"citizenship":"BY","Year":2005,"CountryOfExploitation":"PL","gender":"Female","ageBroad":"Adult","Count":11},{"citizenship":"BY","Year":2005,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult","Count":52},{"citizenship":"BY","Year":2005,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult-","Count":36},{"citizenship":"BY","Year":2005,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Youth","Count":20},{"citizenship":"BY","Year":2005,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult","Count":70},{"citizenship":"BY","Year":2005,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult+","Count":13},{"citizenship":"BY","Year":2005,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult-","Count":12},{"citizenship":"BY","Year":2005,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Youth","Count":14},{"citizenship":"GH","Year":2005,"CountryOfExploitation":"GH","gender":"Female","ageBroad":"Youth","Count":206},{"citizenship":"GH","Year":2005,"CountryOfExploitation":"GH","gender":"Male","ageBroad":"Youth","Count":308},{"citizenship":"ID","Year":2005,"CountryOfExploitation":"MY","gender":"Female","ageBroad":"Adult","Count":11},{"citizenship":"MD","Year":2005,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult","Count":123},{"citizenship":"MD","Year":2005,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult-","Count":61},{"citizenship":"MD","Year":2005,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Youth","Count":15},{"citizenship":"RO","Year":2005,"CountryOfExploitation":"IT","gender":"Female","ageBroad":"Adult-","Count":16},{"citizenship":"RO","Year":2005,"CountryOfExploitation":"RO","gender":"Female","ageBroad":"Adult","Count":50},{"citizenship":"RO","Year":2005,"CountryOfExploitation":"RO","gender":"Female","ageBroad":"Adult-","Count":77},{"citizenship":"TJ","Year":2005,"CountryOfExploitation":"TJ","gender":"Female","ageBroad":"Adult","Count":45},{"citizenship":"UA","Year":2005,"CountryOfExploitation":"BG","gender":"Female","ageBroad":"Adult","Count":14},{"citizenship":"UA","Year":2005,"CountryOfExploitation":"PL","gender":"Female","ageBroad":"Adult","Count":11},{"citizenship":"UA","Year":2005,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult","Count":18},{"citizenship":"UA","Year":2005,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult-","Count":13},{"citizenship":"UA","Year":2005,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult","Count":11},{"citizenship":"UA","Year":2005,"CountryOfExploitation":"TR","gender":"Female","ageBroad":"Adult","Count":67},{"citizenship":"UA","Year":2005,"CountryOfExploitation":"TR","gender":"Female","ageBroad":"Adult-","Count":40},{"citizenship":"UZ","Year":2005,"CountryOfExploitation":"UZ","gender":"Female","ageBroad":"Adult","Count":67},{"citizenship":"UZ","Year":2005,"CountryOfExploitation":"UZ","gender":"Female","ageBroad":"Adult-","Count":11},{"citizenship":"BY","Year":2006,"CountryOfExploitation":"PL","gender":"Female","ageBroad":"Adult","Count":12},{"citizenship":"BY","Year":2006,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult","Count":67},{"citizenship":"BY","Year":2006,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult-","Count":27},{"citizenship":"BY","Year":2006,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult","Count":120},{"citizenship":"BY","Year":2006,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult+","Count":19},{"citizenship":"BY","Year":2006,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult-","Count":12},{"citizenship":"GH","Year":2006,"CountryOfExploitation":"GH","gender":"Male","ageBroad":"Youth","Count":31},{"citizenship":"ID","Year":2006,"CountryOfExploitation":"ID","gender":"Female","ageBroad":"Adult","Count":21},{"citizenship":"ID","Year":2006,"CountryOfExploitation":"MY","gender":"Female","ageBroad":"Adult","Count":265},{"citizenship":"ID","Year":2006,"CountryOfExploitation":"MY","gender":"Female","ageBroad":"Adult-","Count":54},{"citizenship":"ID","Year":2006,"CountryOfExploitation":"MY","gender":"Female","ageBroad":"Youth","Count":27},{"citizenship":"MD","Year":2006,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult","Count":118},{"citizenship":"MD","Year":2006,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult-","Count":65},{"citizenship":"MD","Year":2006,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Youth","Count":61},{"citizenship":"MD","Year":2006,"CountryOfExploitation":"MD","gender":"Male","ageBroad":"Youth","Count":26},{"citizenship":"MD","Year":2006,"CountryOfExploitation":"TR","gender":"Female","ageBroad":"Adult-","Count":23},{"citizenship":"RO","Year":2006,"CountryOfExploitation":"RO","gender":"Female","ageBroad":"Adult","Count":34},{"citizenship":"RO","Year":2006,"CountryOfExploitation":"RO","gender":"Female","ageBroad":"Adult-","Count":61},{"citizenship":"RO","Year":2006,"CountryOfExploitation":"RO","gender":"Female","ageBroad":"Youth","Count":14},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"AE","gender":"Female","ageBroad":"Adult","Count":17},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"AE","gender":"Female","ageBroad":"Adult-","Count":15},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"CZ","gender":"Female","ageBroad":"Adult","Count":30},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"PL","gender":"Female","ageBroad":"Adult","Count":121},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"PL","gender":"Male","ageBroad":"Adult","Count":15},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult","Count":79},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult-","Count":42},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Youth","Count":11},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult","Count":74},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"TR","gender":"Female","ageBroad":"Adult","Count":54},{"citizenship":"UA","Year":2006,"CountryOfExploitation":"TR","gender":"Female","ageBroad":"Adult-","Count":19},{"citizenship":"BG","Year":2007,"CountryOfExploitation":"BG","gender":"Female","ageBroad":"Adult","Count":153},{"citizenship":"BG","Year":2007,"CountryOfExploitation":"BG","gender":"Female","ageBroad":"Adult-","Count":46},{"citizenship":"BG","Year":2007,"CountryOfExploitation":"BG","gender":"Female","ageBroad":"Youth","Count":27},{"citizenship":"BY","Year":2007,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult","Count":11},{"citizenship":"BY","Year":2007,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult-","Count":15},{"citizenship":"CD","Year":2007,"CountryOfExploitation":"UG","gender":"Female","ageBroad":"Youth","Count":25},{"citizenship":"CD","Year":2007,"CountryOfExploitation":"UG","gender":"Male","ageBroad":"Youth","Count":28},{"citizenship":"CI","Year":2007,"CountryOfExploitation":"SN","gender":"Male","ageBroad":"Youth","Count":31},{"citizenship":"GW","Year":2007,"CountryOfExploitation":"SN","gender":"Male","ageBroad":"Youth","Count":85},{"citizenship":"ID","Year":2007,"CountryOfExploitation":"MY","gender":"Female","ageBroad":"Adult","Count":76},{"citizenship":"ID","Year":2007,"CountryOfExploitation":"MY","gender":"Female","ageBroad":"Adult-","Count":17},{"citizenship":"ID","Year":2007,"CountryOfExploitation":"MY","gender":"Female","ageBroad":"Youth","Count":13},{"citizenship":"MD","Year":2007,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult","Count":130},{"citizenship":"MD","Year":2007,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult-","Count":49},{"citizenship":"MD","Year":2007,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Youth","Count":74},{"citizenship":"MD","Year":2007,"CountryOfExploitation":"MD","gender":"Male","ageBroad":"Youth","Count":40},{"citizenship":"ML","Year":2007,"CountryOfExploitation":"SN","gender":"Female","ageBroad":"Youth","Count":19},{"citizenship":"RO","Year":2007,"CountryOfExploitation":"RO","gender":"Female","ageBroad":"Adult","Count":16},{"citizenship":"RO","Year":2007,"CountryOfExploitation":"RO","gender":"Female","ageBroad":"Adult-","Count":21},{"citizenship":"SN","Year":2007,"CountryOfExploitation":"SN","gender":"Male","ageBroad":"Youth","Count":14},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"AE","gender":"Female","ageBroad":"Adult","Count":38},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"AE","gender":"Female","ageBroad":"Adult-","Count":30},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"AT","gender":"Female","ageBroad":"Adult","Count":24},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"CZ","gender":"Female","ageBroad":"Adult","Count":24},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"PL","gender":"Female","ageBroad":"Adult","Count":77},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"PL","gender":"Female","ageBroad":"Adult-","Count":11},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult","Count":57},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult-","Count":20},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult","Count":136},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult-","Count":11},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"TR","gender":"Female","ageBroad":"Adult","Count":41},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"TR","gender":"Female","ageBroad":"Adult-","Count":18},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"UA","gender":"Female","ageBroad":"Adult","Count":81},{"citizenship":"UA","Year":2007,"CountryOfExploitation":"UA","gender":"Female","ageBroad":"Adult-","Count":11},{"citizenship":"BY","Year":2008,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult","Count":11},{"citizenship":"GN","Year":2008,"CountryOfExploitation":"SN","gender":"Male","ageBroad":"Youth","Count":15},{"citizenship":"KG","Year":2008,"CountryOfExploitation":"KZ","gender":"Male","ageBroad":"Adult","Count":11},{"citizenship":"MD","Year":2008,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult","Count":87},{"citizenship":"MD","Year":2008,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult-","Count":56},{"citizenship":"MD","Year":2008,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Youth","Count":50},{"citizenship":"MD","Year":2008,"CountryOfExploitation":"MD","gender":"Male","ageBroad":"Youth","Count":48},{"citizenship":"RO","Year":2008,"CountryOfExploitation":"IT","gender":"Female","ageBroad":"Adult-","Count":12},{"citizenship":"SL","Year":2008,"CountryOfExploitation":"SL","gender":"Female","ageBroad":"Youth","Count":40},{"citizenship":"SL","Year":2008,"CountryOfExploitation":"SL","gender":"Male","ageBroad":"Youth","Count":25},{"citizenship":"SN","Year":2008,"CountryOfExploitation":"SN","gender":"Male","ageBroad":"Youth","Count":12},{"citizenship":"UA","Year":2008,"CountryOfExploitation":"UA","gender":"Female","ageBroad":"Adult","Count":351},{"citizenship":"UA","Year":2008,"CountryOfExploitation":"UA","gender":"Female","ageBroad":"Adult-","Count":46},{"citizenship":"UA","Year":2008,"CountryOfExploitation":"UA","gender":"Female","ageBroad":"Youth","Count":12},{"citizenship":"UA","Year":2008,"CountryOfExploitation":"UA","gender":"Male","ageBroad":"Adult","Count":52},{"citizenship":"MD","Year":2009,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult","Count":171},{"citizenship":"MD","Year":2009,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult-","Count":46},{"citizenship":"MD","Year":2009,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Youth","Count":135},{"citizenship":"MD","Year":2009,"CountryOfExploitation":"MD","gender":"Male","ageBroad":"Adult-","Count":15},{"citizenship":"MD","Year":2009,"CountryOfExploitation":"MD","gender":"Male","ageBroad":"Youth","Count":97},{"citizenship":"UA","Year":2009,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult","Count":24},{"citizenship":"UA","Year":2009,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult","Count":14},{"citizenship":"UA","Year":2009,"CountryOfExploitation":"UA","gender":"Female","ageBroad":"Adult","Count":242},{"citizenship":"UA","Year":2009,"CountryOfExploitation":"UA","gender":"Female","ageBroad":"Adult-","Count":34},{"citizenship":"UA","Year":2009,"CountryOfExploitation":"UA","gender":"Female","ageBroad":"Youth","Count":14},{"citizenship":"Unknown","Year":2009,"CountryOfExploitation":"EC","gender":"Unknown","ageBroad":"Unknown","Count":30},{"citizenship":"Unknown","Year":2009,"CountryOfExploitation":"TT","gender":"Unknown","ageBroad":"Unknown","Count":11},{"citizenship":"BF","Year":2010,"CountryOfExploitation":"SN","gender":"Male","ageBroad":"Adult-","Count":14},{"citizenship":"BF","Year":2010,"CountryOfExploitation":"SN","gender":"Male","ageBroad":"Youth","Count":19},{"citizenship":"BY","Year":2010,"CountryOfExploitation":"RU","gender":"Female","ageBroad":"Adult","Count":14},{"citizenship":"CO","Year":2010,"CountryOfExploitation":"EC","gender":"Female","ageBroad":"Adult","Count":13},{"citizenship":"GW","Year":2010,"CountryOfExploitation":"SN","gender":"Male","ageBroad":"Youth","Count":60},{"citizenship":"KG","Year":2010,"CountryOfExploitation":"KZ","gender":"Male","ageBroad":"Adult","Count":45},{"citizenship":"KG","Year":2010,"CountryOfExploitation":"RU","gender":"Male","ageBroad":"Adult","Count":44},{"citizenship":"KG","Year":2010,"CountryOfExploitation":"Unknown","gender":"Male","ageBroad":"Adult","Count":11},{"citizenship":"KH","Year":2010,"CountryOfExploitation":"TH","gender":"Female","ageBroad":"Youth","Count":17},{"citizenship":"KH","Year":2010,"CountryOfExploitation":"TH","gender":"Male","ageBroad":"Youth","Count":35},{"citizenship":"KZ","Year":2010,"CountryOfExploitation":"KZ","gender":"Female","ageBroad":"Adult-","Count":13},{"citizenship":"LA","Year":2010,"CountryOfExploitation":"TH","gender":"Female","ageBroad":"Youth","Count":130},{"citizenship":"MD","Year":2010,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult","Count":170},{"citizenship":"MD","Year":2010,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult+","Count":11},{"citizenship":"MD","Year":2010,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Adult-","Count":61},{"citizenship":"MD","Year":2010,"CountryOfExploitation":"MD","gender":"Female","ageBroad":"Youth","Count":177},{"citizenship":"MD","Year":2010,"CountryOfExploitation":"MD","gender":"Male","ageBroad":"Adult-","Count":17},{"citizenship":"MD","Year":2010,"CountryOfExploitation":"MD","gender":"Male","ageBroad

In [12]:
query = "select * from gdp"
df = pd.read_sql(query, engine)
df.head()

  Country Name Country Code  Years  GPD Values
0  Afghanistan           AF   1990         0.0
1  Afghanistan           AF   1991         0.0
2  Afghanistan           AF   1992         0.0
3  Afghanistan           AF   1993         0.0
4  Afghanistan           AF   1994         0.0