In [1]:
import pprint
import pandas
import geopandas
from pandas.io.json import json_normalize
import geojson

import json
import numpy
import math

In [2]:
with open('globe.geo.json') as f:
    data = geojson.load(f)
nestedglobe = pandas.DataFrame(data)
# globe['features'][1]
nestedglobe['features'][0]

{"geometry": {"coordinates": [[[-79.98928788999987, 15.794948635000056], [-79.9878230459999, 15.796210028000074], [-79.98639889199991, 15.794419664000086], [-79.98814856699991, 15.79417552300012], [-79.98928788999987, 15.794948635000056]]], "type": "Polygon"}, "properties": {"abbrev": null, "abbrev_len": 0, "adm0_a3": "BJN", "adm0_a3_is": "-99", "adm0_a3_un": -99, "adm0_a3_us": "B41", "adm0_a3_wb": -99, "adm0_dif": 0, "admin": "Bajo Nuevo Bank (Petrel Is.)", "brk_a3": "B41", "brk_diff": 1, "brk_group": null, "brk_name": "Bajo Nuevo Bank (Petrel Is.)", "continent": "North America", "economy": "7. Least developed region", "featurecla": "Admin-0 country", "filename": "bajonuevobankpetrelis.geojson", "fips_10_": "-99", "formal_en": null, "formal_fr": null, "gdp_md_est": -99, "gdp_year": 2012, "geou_dif": 0, "geounit": "Bajo Nuevo Bank (Petrel Is.)", "gu_a3": "BJN", "homepart": 1, "income_grp": "5. Low income", "iso_a2": "-99", "iso_a3": "-99", "iso_n3": "-99", "labelrank": 8, "lastcensus": -99, "level": 2, "long_len": 32, "mapcolor13": -99, "mapcolor7": 3, "mapcolor8": 7, "mapcolor9": 6, "name": "Bajo Nuevo Bank (Petrel Is.)", "name_alt": null, "name_len": 28, "name_long": "Bajo Nuevo Bank (Petrel Islands)", "name_sort": "Bajo Nuevo Bank (Petrel Is.)", "note_adm0": "Disputed", "note_brk": "Claimed by Columbia, Jamaica, Nicaragua and the United States", "pop_est": -99, "pop_year": 2012, "postal": null, "region_un": "Americas", "region_wb": "Latin America & Caribbean", "scalerank": 6, "sov_a3": "BJN", "sovereignt": "Bajo Nuevo Bank (Petrel Is.)", "su_a3": "BJN", "su_dif": 0, "subregion": "Caribbean", "subunit": "Bajo Nuevo Bank (Petrel Is.)", "tiny": -99, "type": "Indeterminate", "un_a3": "-099", "wb_a2": "-99", "wb_a3": "-99", "wikipedia": -99, "woe_id": -99, "woe_id_eh": -99, "woe_note": "No WOE equivalent."}, "type": "Feature"}

In [3]:
globe = pandas.io.json.json_normalize(nestedglobe['features'])
globe = globe.drop(['properties.abbrev', 'properties.abbrev_len',
              'properties.adm0_a3', 'properties.adm0_a3_is', 'properties.adm0_a3_un',
            'properties.adm0_a3_wb', 'properties.adm0_dif', 'properties.brk_diff',
             'properties.adm0_a3_us', 'properties.brk_a3', 'properties.brk_group',
             'properties.brk_name', 'properties.featurecla', 'properties.tiny',
             'properties.filename', 'properties.fips_10_', 'properties.formal_en',
             'properties.formal_fr', 'properties.gdp_md_est', 'properties.gdp_year',
             'properties.geounit', 'properties.subunit', 'properties.geou_dif', 
             'properties.gu_a3', 'properties.homepart', 'properties.iso_a3', 
              'properties.un_a3', 'properties.wb_a2', 'properties.wb_a3',
             'properties.wikipedia', 'properties.labelrank', 'properties.lastcensus',
             'properties.level', 'properties.sov_a3', 'properties.su_a3',
             'properties.su_dif', 'properties.subregion', 'properties.woe_id', 
             'properties.woe_note', 'properties.woe_id_eh', 'properties.long_len',
             'properties.mapcolor13','properties.mapcolor9','properties.mapcolor8',
             'properties.mapcolor7', 'properties.admin', 'properties.name_alt', 'properties.note_brk',
             'properties.postal', 'properties.pop_est', 'properties.pop_year', 
             'properties.note_brk', 'properties.region_un', 'properties.scalerank',
             'properties.iso_n3', 'properties.name_long', 'properties.name_sort',
             'properties.name_len', 'properties.region_wb', 'properties.note_adm0',
            'properties.continent', 'type'
             ], axis=1)
# df = df.set_index('properties.admin', drop=True)
globe.rename(columns = {'properties.iso_a2': 'properties.code'}, inplace=True)
globe['properties.code'] = globe['properties.code'].astype(str)
globe.sort_values('properties.code').head(250)

,geometry.coordinates,geometry.type,properties.economy,properties.income_grp,properties.code,properties.name,properties.sovereignt,properties.type
0,"[[[-79.98928788999987, 15.794948635000056], [-...",Polygon,7. Least developed region,5. Low income,-99,Bajo Nuevo Bank (Petrel Is.),Bajo Nuevo Bank (Petrel Is.),Indeterminate
41,"[[[123.59701582100011, -12.428317966999899], [...",Polygon,7. Least developed region,5. Low income,-99,Ashmore and Cartier Is.,Australia,Dependency
42,"[[[154.3912866550001, -21.030043226999865], [1...",Polygon,7. Least developed region,5. Low income,-99,Coral Sea Is.,Australia,Dependency
87,"[[[[55.5013126960001, -20.87322356599999], [55...",MultiPolygon,1. Developed region: G7,1. High income: OECD,-99,France,France,Country
94,"[[[20.864700154000047, 43.217337342000036], [2...",Polygon,6. Developing region,4. Lower middle income,-99,Kosovo,Kosovo,Sovereign country
26,"[[[-78.63707434799987, 15.862087307000108], [-...",Polygon,7. Least developed region,5. Low income,-99,Serranilla Bank,Serranilla Bank,Indeterminate
111,"[[[[3.382578972000089, -54.44931405999998], [3...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,-99,Norway,Norway,Sovereign country
160,"[[[48.939111999908164, 11.249129976335054], [4...",Polygon,6. Developing region,4. Lower middle income,-99,Somaliland,Somaliland,Indeterminate
180,"[[[33.905867961000126, 35.09088246600004], [33...",Polygon,2. Developed region: nonG7,2. High income: nonOECD,-99,Dhekelia,United Kingdom,Dependency
182,"[[[[32.626204468000225, 35.165089824000134], [...",MultiPolygon,6. Developing region,3. Upper middle income,-99,N. Cyprus,Northern Cyprus,Sovereign country
183,"[[[[33.92540165200015, 35.06277048700004], [33...",MultiPolygon,6. Developing region,2. High income: nonOECD,-99,Cyprus U.N. Buffer Zone,Cyprus No Mans Area,Indeterminate
40,"[[[[-75.18395510799986, 19.93359416400007], [-...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,-99,USNB Guantanamo Bay,Cuba,Lease
192,"[[[63.3839136150001, 45.56582448300014], [63.3...",Polygon,2. Developed region: nonG7,3. Upper middle income,-99,Baikonur,Kazakhstan,Lease
187,"[[[[96.9139103520001, -12.194512627999854], [9...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,-99,Indian Ocean Ter.,Australia,Dependency
218,"[[[117.753887178, 15.154369263000063], [117.75...",Polygon,7. Least developed region,5. Low income,-99,Scarborough Reef,Scarborough Reef,Indeterminate
228,"[[[32.84080876400009, 34.69946744100013], [32....",Polygon,2. Developed region: nonG7,2. High income: nonOECD,-99,Akrotiri,United Kingdom,Dependency
206,"[[[[114.37647545700004, 9.68012116100013], [11...",MultiPolygon,7. Least developed region,5. Low income,-99,Spratly Is.,Spratly Islands,Indeterminate
195,"[[[76.97641727700011, 35.57865631200005], [77....",Polygon,6. Developing region,4. Lower middle income,-99,Siachen Glacier,Kashmir,Indeterminate
68,"[[[1.707006470000067, 42.5027814740001], [1.69...",Polygon,2. Developed region: nonG7,2. High income: nonOECD,AD,Andorra,Andorra,Sovereign country
178,"[[[[53.863047722, 24.234686591000138], [53.888...",MultiPolygon,6. Developing region,2. High income: nonOECD,AE,United Arab Emirates,United Arab Emirates,Sovereign country
172,"[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,AF,Afghanistan,Afghanistan,Sovereign country
7,"[[[[-61.773019985999916, 17.126532294000143], ...",MultiPolygon,6. Developing region,3. Upper middle income,AG,Antigua and Barb.,Antigua and Barbuda,Sovereign country
1,"[[[[-63.037668423999946, 18.212958075000028], ...",MultiPolygon,6. Developing region,3. Upper middle income,AI,Anguilla,United Kingdom,Dependency
69,"[[[19.747765747000074, 42.57890085900007], [19...",Polygon,6. Developing region,4. Lower middle income,AL,Albania,Albania,Sovereign country
174,"[[[[45.54717289200002, 40.62155263300009], [45...",MultiPolygon,6. Developing region,4. Lower middle income,AM,Armenia,Armenia,Sovereign country
116,"[[[[11.73751945100014, -16.692577982999833], [...",MultiPolygon,7. Least developed region,3. Upper middle income,AO,Angola,Angola,Sovereign country
232,"[[[[-68.65412350199998, -54.88624439899996], [...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,AR,Argentina,Argentina,Sovereign country
39,"[[[[-168.16047115799995, -14.520928643999968],...",MultiPolygon,6. Developing region,3. Upper middle income,AS,American Samoa,United States of America,Dependency
71,"[[[15.161792440000113, 48.93722076400007], [15...",Polygon,2. Developed region: nonG7,1. High income: OECD,AT,Austria,Austria,Sovereign country
55,"[[[[158.86573326900012, -54.749932549999826], ...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,AU,Australia,Australia,Country
...,...,...,...,...,...,...,...,...
222,"[[[[99.247813347, 6.57485586100016], [99.26026...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,TH,Thailand,Thailand,Sovereign country
220,"[[[[70.61990604700006, 39.85069529200014], [70...",MultiPolygon,6. Developing region,5. Low income,TJ,Tajikistan,Tajikistan,Sovereign country
221,"[[[[124.35455896000016, -9.364181823999871], [...",MultiPolygon,7. Least developed region,4. Lower middle income,TL,Timor-Leste,East Timor,Sovereign country
224,"[[[[53.10206139400006, 38.755072333], [53.0947...",MultiPolygon,6. Developing region,3. Upper middle income,TM,Turkmenistan,Turkmenistan,Sovereign country
165,"[[[[10.929942254000082, 33.896307684000035], [...",MultiPolygon,6. Developing region,3. Upper middle income,TN,Tunisia,Tunisia,Sovereign country
61,"[[[[-176.20702063699989, -22.33879973799992], ...",MultiPolygon,6. Developing region,4. Lower middle income,TO,Tonga,Tonga,Sovereign country
227,"[[[[26.04004967500012, 39.84503815300015], [26...",MultiPolygon,4. Emerging region: MIKT,3. Upper middle income,TR,Turkey,Turkey,Sovereign country
34,"[[[[-60.90729732999998, 10.837144273000163], [...",MultiPolygon,6. Developing region,2. High income: nonOECD,TT,Trinidad and Tobago,Trinidad and Tobago,Sovereign country
60,"[[[[179.90609785200013, -9.418633721999868], [...",MultiPolygon,7. Least developed region,3. Upper middle income,TV,Tuvalu,Tuvalu,Sovereign country
225,"[[[[121.58765709700006, 22.013861395], [121.56...",MultiPolygon,2. Developed region: nonG7,2. High income: nonOECD,TW,Taiwan,Taiwan,Sovereign country
168,"[[[[39.74916454600012, -8.065492432999873], [3...",MultiPolygon,7. Least developed region,5. Low income,TZ,Tanzania,United Republic of Tanzania,Sovereign country
113,"[[[[29.807465040000153, 45.614325262000094], [...",MultiPolygon,6. Developing region,4. Lower middle income,UA,Ukraine,Ukraine,Sovereign country
166,"[[[34.10802616400014, 3.868938091000103], [34....",Polygon,7. Least developed region,5. Low income,UG,Uganda,Uganda,Sovereign country
36,"[[[[-160.0124405589999, -0.382094007999925], [...",MultiPolygon,7. Least developed region,5. Low income,UM,U.S. Minor Outlying Is.,United States of America,Dependency
57,"[[[[-155.6065189699999, 20.137955566000144], [...",MultiPolygon,1. Developed region: G7,1. High income: OECD,US,United States,United States of America,Country
240,"[[[-56.90636673999998, -30.108548685999907], [...",Polygon,5. Emerging region: G20,3. Upper middle income,UY,Uruguay,Uruguay,Sovereign country
226,"[[[[71.75730432100013, 39.9030951940001], [71....",MultiPolygon,6. Developing region,4. Lower middle income,UZ,Uzbekistan,Uzbekistan,Sovereign country
115,"[[[12.45313691700008, 41.902751941000105], [12...",Polygon,2. Developed region: nonG7,2. High income: nonOECD,VA,Vatican,Vatican,Sovereign country
37,"[[[[-61.43272864499988, 12.587836005000113], [...",MultiPolygon,6. Developing region,3. Upper middle income,VC,St. Vin. and Gren.,Saint Vincent and the Grenadines,Sovereign country
243,"[[[[-61.39027141599987, 8.580580853000143], [-...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,VE,Venezuela,Venezuela,Sovereign country
38,"[[[[-64.56786048099994, 18.337388414000046], [...",MultiPolygon,2. Developed region: nonG7,1. High income: OECD,VG,British Virgin Is.,United Kingdom,Dependency
43,"[[[[-64.73078365799995, 17.765285549000126], [...",MultiPolygon,6. Developing region,2. High income: nonOECD,VI,U.S. Virgin Is.,United States of America,Dependency
231,"[[[[106.66871178500006, 8.753485419000171], [1...",MultiPolygon,5. Emerging region: G20,4. Lower middle income,VN,Vietnam,Vietnam,Sovereign country
62,"[[[[169.83814537900005, -20.248630466999856], ...",MultiPolygon,7. Least developed region,4. Lower middle income,VU,Vanuatu,Vanuatu,Sovereign country
65,"[[[[-178.0467423169999, -14.312595309999978], ...",MultiPolygon,6. Developing region,4. Lower middle income,WF,Wallis and Futuna Is.,France,Dependency
66,"[[[[-171.5700170559999, -13.938164971999923], ...",MultiPolygon,7. Least developed region,4. Lower middle income,WS,Samoa,Samoa,Sovereign country
229,"[[[[53.308239457000155, 12.11839453700017], [5...",MultiPolygon,7. Least developed region,4. Lower middle income,YE,Yemen,Yemen,Sovereign country
170,"[[[[37.86378014400023, -46.94085051899984], [3...",MultiPolygon,5. Emerging region: G20,3. Upper middle income,ZA,South Africa,South Africa,Sovereign country
169,"[[[31.11983646700014, -8.616630553999912], [31...",Polygon,7. Least developed region,4. Lower middle income,ZM,Zambia,Zambia,Sovereign country
171,"[[[30.010653524000077, -15.64622731499989], [3...",Polygon,5. Emerging region: G20,5. Low income,ZW,Zimbabwe,Zimbabwe,Sovereign country

In [4]:
trafficking = pandas.read_csv('trafficking.csv',low_memory=False)
trafficking = trafficking.drop(trafficking.columns[[0, 2]], axis=1)
trafficking = trafficking.replace(['-99','18--20', '24--26', '30--38', '21--23',
                           '27--29', '9--17','39--47', '48+', '0--8',
                           'Unknown'], ['Unknown','Adult-', 'Adult', 'Adult', 'Adult',
                                        'Adult', 'Youth', 'Adult', 'Adult+', 'Youth', 
                                            'ZZ'])
trafficking = trafficking.rename(columns={'yearOfRegistration':"Year"})
trafficking = trafficking[['Year', 'gender', 'ageBroad','citizenship','CountryOfExploitation']]
trafficking.head(5)

   Year gender ageBroad citizenship CountryOfExploitation
0  2002     ZZ       ZZ          ZZ                    ZZ
1  2002     ZZ       ZZ          ZZ                    ZZ
2  2002     ZZ       ZZ          ZZ                    ZZ
3  2002     ZZ       ZZ          ZZ                    ZZ
4  2002     ZZ       ZZ          ZZ                    ZZ

In [5]:
traffickingCounts = trafficking.groupby(['citizenship', "Year","CountryOfExploitation"],
                 as_index=False).count().iloc[:,:-1]\
                .rename(columns={'citizenship':'properties.code','gender':'CaseCount'})
#                        .set_index(['citizenship', 'Year']) \
traffickingCounts.head()

  properties.code  Year CountryOfExploitation  CaseCount
0              AF  2013                    AF         12
1              AF  2013                    ZZ         25
2              AF  2014                    AF         72
3              AF  2014                    ZZ        116
4              AF  2015                    SA         14

In [6]:
longcounts = traffickingCounts[['properties.code', "Year"]].drop_duplicates()
for index,row in traffickingCounts.iterrows():

    col = row[2]
    longcounts.loc[(longcounts['properties.code'] == row[0]) & (longcounts["Year"] == row[1]),
                   "Total"] = traffickingCounts.loc[
                            (traffickingCounts['properties.code'] == row[0]) &
                            (traffickingCounts["Year"] == row[1])]['CaseCount'].sum()

#     EACH COUNTRY

    longcounts.loc[(longcounts['properties.code'] == row[0]) &  (longcounts["Year"] == row[1]),
               col] = traffickingCounts.loc[
                        (traffickingCounts['properties.code'] == row[0]) &
                        (traffickingCounts["Year"] == row[1]) &
                        (traffickingCounts['CountryOfExploitation'] == col)]['CaseCount'].values[0]



longcounts.reset_index().to_json("TraffickingCounts.json", orient="records")

In [7]:
# Total = traffickingCounts.T.sum().reset_index().rename(columns={0:"TotalTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalFemale = traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('Female')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalFemaleTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalMale = traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('Male')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalMaleTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalChild =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('Child')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalChildTrafficked"})\
# .set_index(['citizenship', 'Year'])


# TotalAdultMinus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('Adult-')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalAdult-Trafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalAdult =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('AdultTraf')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalAdultTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalAdultPlus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('Adult+')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalAdult+Trafficked"})\
# .set_index(['citizenship', 'Year'])


# TotalMaleChild =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('MaleChild')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalMaleChildTrafficked"})\
# .set_index(['citizenship', 'Year'])


# TotalMaleAdultMinus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('MaleAdult-')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalMaleAdult-Trafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalMaleAdult =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('MaleAdultTraf')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalMaleAdultTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalMaleAdultPlus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('MaleAdult+')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalMaleAdult+Trafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalFemaleChild =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('MaleChild')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalFemaleChildTrafficked"})\
# .set_index(['citizenship', 'Year'])


# TotalFemaleAdultMinus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('FemaleAdult-')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalFemaleAdult-Trafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalFemaleAdult =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('FemaleAdultTraf')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalFemaleAdultTrafficked"})\
# .set_index(['citizenship', 'Year'])

# TotalFemaleAdultPlus =  traffickingCounts[traffickingCounts.columns[traffickingCounts \
#                                             .columns.to_series().str.contains('FemaleAdult+')]] \
#                                             .T.sum().reset_index().rename(columns={0:"TotalFemaleAdult+Trafficked"})\
# .set_index(['citizenship', 'Year'])


# FinalTotals = pandas.concat([Total, TotalChild, TotalAdult,
#                  TotalAdultMinus, TotalAdultPlus, TotalFemale, TotalMale,
#                  TotalMaleChild, TotalMaleAdultMinus, TotalMaleAdult, TotalMaleAdultPlus,
#                 TotalFemaleChild,TotalFemaleAdultMinus, TotalFemaleAdult, TotalFemaleAdultPlus],axis=1, join='outer')

In [8]:
gdp = pandas.read_csv('Countries_GDP_Cleaned.csv')
gdp = pandas.DataFrame(gdp)
gdp = gdp.rename(columns={'Country Code':'properties.code'})
gdp = gdp.rename(columns={'GPD':'GDP(ppp)', 'Country Name':'Name', "Years":'Year'})
gdp.tail()

          Name properties.code  Year      GDP(ppp)
6015  Zimbabwe              ZW  2013  3.006463e+10
6016  Zimbabwe              ZW  2014  3.125517e+10
6017  Zimbabwe              ZW  2015  3.212793e+10
6018  Zimbabwe              ZW  2016  3.273816e+10
6019  Zimbabwe              ZW  2017  3.447604e+10

In [9]:
 def colorPick(gdp_md_est):
        

    if gdp_md_est > 1088982000000:
        color = "#7FFF00"
    elif gdp_md_est > 367301000000:
        color = "#98FB98"
    elif gdp_md_est > 171588000000:
        color = "#87CEFA"
    elif gdp_md_est > 71926000000:
        color = "#F0E68C"
    elif gdp_md_est > 34633000000:
        color = "#F4A460"
    elif gdp_md_est > 19688000000:
        color = "#FF4500"
    elif gdp_md_est > 3165000000:
        color = "#8B0000"
    elif type(gdp_md_est) != "float64":
        color = "#FFFFFF"
    
    
    else:
        color = '#FFFFFF'

    return color

In [10]:
for index,row in gdp.iterrows():
    gdp['color'] = gdp['GDP(ppp)'].apply(colorPick)
gdp.head(5)

          Name properties.code  Year  GDP(ppp)    color
0  Afghanistan              AF  1990       0.0  #FFFFFF
1  Afghanistan              AF  1991       0.0  #FFFFFF
2  Afghanistan              AF  1992       0.0  #FFFFFF
3  Afghanistan              AF  1993       0.0  #FFFFFF
4  Afghanistan              AF  1994       0.0  #FFFFFF

In [11]:
TraffickedWithGdp = pandas.merge(longcounts,gdp, on=['properties.code', 'Year'],
                                 how='left').sort_values(['properties.code'])

TraffickedWithGdp.head(25)
longcounts[longcounts['properties.code']=='RU']

Empty DataFrame
Columns: [properties.code, Year, Total, AF, ZZ, SA, AL, TJ, SN, BG, AR, AE, CY, RU, PL, BY, UG, US, EC, EG, GH, HT, MY, ID, BH, JO, OM, QA, SG, SY, TT, TW, ZA, KZ, TH, MU, CN, KH, Y1, MD, TR, UA, MG, LB, JP, KW, PH, HK, BA, MK, IT, RO, DK, SL, TM, CZ, AT, UZ, VN, MX]
Index: []

[0 rows x 60 columns]

In [12]:
TraffickedWithGdp['TraffickingStats'] = [{k:v for k,v in m.items()  \
                                      if pandas.notnull(v)} for m in \
                                     TraffickedWithGdp.iloc[:,2:-3].to_dict(orient='rows')]
    
TraffickedWithGdp = TraffickedWithGdp.drop(TraffickedWithGdp.iloc[:,2:-3], axis=1)
TraffickedWithGdp.head()

,properties.code,Year,GDP(ppp),color,TraffickingStats
0,AF,2013,6.070782e+10,#F4A460,"{'AF': 12.0, 'ZZ': 25.0, 'Total': 37.0}"
1,AF,2014,6.345999e+10,#F4A460,"{'AF': 72.0, 'ZZ': 116.0, 'Total': 188.0}"
2,AF,2015,6.498854e+10,#F4A460,"{'SA': 14.0, 'Total': 14.0}"
3,AL,2005,1.789692e+10,#8B0000,"{'AL': 45.0, 'Total': 45.0}"
4,BD,2015,5.380000e+11,#98FB98,"{'TJ': 11.0, 'Total': 11.0}"

In [13]:
def halfwayPoints(df, column):
    allMidPoints = []
    for _, row in df.iterrows():
        midPoints = []
        lastcoord = 0
        counter = 0
        for coord in row[column][0]:
                print(coord)
                
                if lastcoord != coord and len(coord) == 2:
                    lastcoord = coord

                    midpoint = [float(lastcoord[0])+float(coord[0]) * 0.5,
                                 float(lastcoord[1]), float(coord[1]) * 0.5 ]
            
                    midPoints.append(midpoint)
                elif  lastcoord != coord[0]:
                    lastcoord = coord[0]

                    midpoint = [float(lastcoord[0])+float(coord[0][0]) * 0.5,
                                 float(lastcoord[1]), float(coord[0][1]) * 0.5 ]
            
                    midPoints.append(midpoint)

        allMidPoints.append(midPoints)
    return allMidPoints

In [14]:
globeFinal = pandas.merge(TraffickedWithGdp, globe, on="properties.code", how="outer")
globeFinal['GDP(ppp)'] = globeFinal['GDP(ppp)'].fillna(-99)
globeFinal['Year'] = globeFinal['Year'].fillna(-99)
globeFinal['color'] = globeFinal['color'].fillna("#708090")
globeFinal = globeFinal[globeFinal['properties.code'] != "ZZ"]
globeFinal = globeFinal[globeFinal['properties.code'] != "-99"]
globeFinal['TraffickingStats'] = globeFinal['TraffickingStats'].fillna("None")

In [15]:
globeFinal[globeFinal.isnull().any(axis=1)]

Empty DataFrame
Columns: [properties.code, Year, GDP(ppp), color, TraffickingStats, geometry.coordinates, geometry.type, properties.economy, properties.income_grp, properties.name, properties.sovereignt, properties.type]
Index: []

In [16]:
globeFinal.head()

,properties.code,Year,GDP(ppp),color,TraffickingStats,geometry.coordinates,geometry.type,properties.economy,properties.income_grp,properties.name,properties.sovereignt,properties.type
0,AF,2013.0,6.070782e+10,#F4A460,"{'AF': 12.0, 'ZZ': 25.0, 'Total': 37.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country
1,AF,2014.0,6.345999e+10,#F4A460,"{'AF': 72.0, 'ZZ': 116.0, 'Total': 188.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country
2,AF,2015.0,6.498854e+10,#F4A460,"{'SA': 14.0, 'Total': 14.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country
3,AL,2005.0,1.789692e+10,#8B0000,"{'AL': 45.0, 'Total': 45.0}","[[[19.747765747000074, 42.57890085900007], [19...",Polygon,6. Developing region,4. Lower middle income,Albania,Albania,Sovereign country
4,BD,2015.0,5.380000e+11,#98FB98,"{'TJ': 11.0, 'Total': 11.0}","[[[[91.9387313160001, 21.714829820000105], [91...",MultiPolygon,7. Least developed region,5. Low income,Bangladesh,Bangladesh,Sovereign country

In [17]:
# dist = math.hypot(x2 - x1, y2 - y1)
def arrowPath (df):
    path_coords = []

    for _, row in df.iterrows():
        path_coord = []
        shortest_path = 4e8
        
        if row['TraffickingStats'] != "None":
            for code in row['TraffickingStats']:
                if code != "ZZ" and code !=  "Total" and code != row['properties.code']:
                    try:
    
                        originCoords = row['geometry.coordinates']
                        destinationCoords = df[df['properties.code']==code]['geometry.coordinates']

                        for polygonA in originCoords:
                            for polygonB in destinationCoords:
    
                                while len(polygonA[0]) != 2 or len(polygonA) == 1:
                                    polygonA = polygonA[0]

                                while len(polygonB[0]) != 2 or len(polygonB) == 1:
                                    polygonB = polygonB[0]

                                for origin in polygonA:
                                    for destination in polygonB:
                                        path =  math.hypot(destination[0] - origin[0],
                                                       destination[1] - origin[1])
                                        if path < shortest_path and path != 0:
                                            shortest_path=path
                                            path_coord = [code, origin, destination, row['TraffickingStats'][code]]

                    except IndexError:
                        print("No coords for", row['properties.code'], code )
                    except KeyError:
                        print("No coords for", row['properties.code'], code )
        path_coords.append(path_coord)
        
    return(path_coords)

In [18]:

globeFinal['arrowPath'] = arrowPath(globeFinal)

In [19]:
globeFinal.head()

,properties.code,Year,GDP(ppp),color,TraffickingStats,geometry.coordinates,geometry.type,properties.economy,properties.income_grp,properties.name,properties.sovereignt,properties.type,arrowPath
0,AF,2013.0,6.070782e+10,#F4A460,"{'AF': 12.0, 'ZZ': 25.0, 'Total': 37.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country,[]
1,AF,2014.0,6.345999e+10,#F4A460,"{'AF': 72.0, 'ZZ': 116.0, 'Total': 188.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country,[]
2,AF,2015.0,6.498854e+10,#F4A460,"{'SA': 14.0, 'Total': 14.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country,"[SA, [60.844378703000075, 29.858178610000067],..."
3,AL,2005.0,1.789692e+10,#8B0000,"{'AL': 45.0, 'Total': 45.0}","[[[19.747765747000074, 42.57890085900007], [19...",Polygon,6. Developing region,4. Lower middle income,Albania,Albania,Sovereign country,[]
4,BD,2015.0,5.380000e+11,#98FB98,"{'TJ': 11.0, 'Total': 11.0}","[[[[91.9387313160001, 21.714829820000105], [91...",MultiPolygon,7. Least developed region,5. Low income,Bangladesh,Bangladesh,Sovereign country,"[TJ, [88.37251753700016, 26.61160675100011], [..."

In [20]:
def df_to_geojson(df, properties):
    geojson = {'type':'FeatureCollection', 'features':[]}
    for _, row in df.iterrows():
        feature = {'type':'Feature',
                   'properties':{},
                   'geometry':{'type': [],'coordinates':[]}}
        feature['geometry']['coordinates'] = row['geometry.coordinates']
        feature['geometry']['type'] = row['geometry.type']
        for prop in properties:
            feature['properties'][prop] = row[prop]
        geojson['features'].append(feature)
    return geojson

In [21]:
nestedglobe['features'][0]

{"geometry": {"coordinates": [[[-79.98928788999987, 15.794948635000056], [-79.9878230459999, 15.796210028000074], [-79.98639889199991, 15.794419664000086], [-79.98814856699991, 15.79417552300012], [-79.98928788999987, 15.794948635000056]]], "type": "Polygon"}, "properties": {"abbrev": null, "abbrev_len": 0, "adm0_a3": "BJN", "adm0_a3_is": "-99", "adm0_a3_un": -99, "adm0_a3_us": "B41", "adm0_a3_wb": -99, "adm0_dif": 0, "admin": "Bajo Nuevo Bank (Petrel Is.)", "brk_a3": "B41", "brk_diff": 1, "brk_group": null, "brk_name": "Bajo Nuevo Bank (Petrel Is.)", "continent": "North America", "economy": "7. Least developed region", "featurecla": "Admin-0 country", "filename": "bajonuevobankpetrelis.geojson", "fips_10_": "-99", "formal_en": null, "formal_fr": null, "gdp_md_est": -99, "gdp_year": 2012, "geou_dif": 0, "geounit": "Bajo Nuevo Bank (Petrel Is.)", "gu_a3": "BJN", "homepart": 1, "income_grp": "5. Low income", "iso_a2": "-99", "iso_a3": "-99", "iso_n3": "-99", "labelrank": 8, "lastcensus": -99, "level": 2, "long_len": 32, "mapcolor13": -99, "mapcolor7": 3, "mapcolor8": 7, "mapcolor9": 6, "name": "Bajo Nuevo Bank (Petrel Is.)", "name_alt": null, "name_len": 28, "name_long": "Bajo Nuevo Bank (Petrel Islands)", "name_sort": "Bajo Nuevo Bank (Petrel Is.)", "note_adm0": "Disputed", "note_brk": "Claimed by Columbia, Jamaica, Nicaragua and the United States", "pop_est": -99, "pop_year": 2012, "postal": null, "region_un": "Americas", "region_wb": "Latin America & Caribbean", "scalerank": 6, "sov_a3": "BJN", "sovereignt": "Bajo Nuevo Bank (Petrel Is.)", "su_a3": "BJN", "su_dif": 0, "subregion": "Caribbean", "subunit": "Bajo Nuevo Bank (Petrel Is.)", "tiny": -99, "type": "Indeterminate", "un_a3": "-099", "wb_a2": "-99", "wb_a3": "-99", "wikipedia": -99, "woe_id": -99, "woe_id_eh": -99, "woe_note": "No WOE equivalent."}, "type": "Feature"}

In [70]:
cols = ['properties.code', 'GDP(ppp)', 'color','TraffickingStats','Year', 
        'properties.economy', 'properties.income_grp', 'properties.name',
        'properties.sovereignt', 'properties.type', 'arrowPath']

In [23]:
for year in globeFinal['Year'].unique():
#     year = str(year)
    with open("../static/data/globe%s.geo.json" %str(year).replace(".0", ""),  'w', encoding='utf-8') as f:
        json.dump(df_to_geojson(globeFinal[globeFinal['Year']==int(year)], cols), f, ensure_ascii=False)

In [ ]:
cols = ['properties.code', 'GDP(ppp)', 'color','TraffickingStats', 
        'properties.economy', 'properties.income_grp', 'properties.name',
        'properties.sovereignt', 'properties.type', ]

noData = globeFinal[globeFinal['TraffickingStats']=='None']
noData = noData

with open('../static/data/noshare.geo.json', 'w', encoding='utf-8') as f:
    json.dump(df_to_geojson(noData, cols), f, ensure_ascii=False)

In [ ]:
"y2U3gQBgiV8Kq2u"
"traffickadmin"

In [52]:
import pymongo

In [65]:
client = pymongo.MongoClient("mongodb://traffickAdmin:y2U3gQBgiV8Kq2u@traffickcluster-shard-00-00-xeuqd.mongodb.net:27017,traffickcluster-shard-00-01-xeuqd.mongodb.net:27017,traffickcluster-shard-00-02-xeuqd.mongodb.net:27017/test?ssl=true&replicaSet=TraffickCluster-shard-0&authSource=admin&retryWrites=true")

In [82]:
db = client.TraffickDB
Trafficking = db.trafficking

In [83]:
cols = ['code', 'GDP(ppp)', 'color','TraffickingStats','Year', 
        'economy', 'income_grp', 'name',
        'sovereignt', 'type', 'arrowPath']
globeFinal['Year'] = globeFinal['Year'].astype('int')
globeFinal = globeFinal.rename(columns={'properties.code':'code',
        'properties.economy': 'economy', 'properties.income_grp' : 'income_grp', 'properties.name': 'name',
        'properties.sovereignt' : 'sovereignt', 'properties.type' : 'type'})
globeFinal.head()

,code,Year,GDP(ppp),color,TraffickingStats,geometry.coordinates,geometry.type,economy,income_grp,name,sovereignt,type,arrowPath
0,AF,2013,6.070782e+10,#F4A460,"{'AF': 12.0, 'ZZ': 25.0, 'Total': 37.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country,[]
1,AF,2014,6.345999e+10,#F4A460,"{'AF': 72.0, 'ZZ': 116.0, 'Total': 188.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country,[]
2,AF,2015,6.498854e+10,#F4A460,"{'SA': 14.0, 'Total': 14.0}","[[[71.04980228700008, 38.40866445000009], [71....",Polygon,7. Least developed region,5. Low income,Afghanistan,Afghanistan,Sovereign country,"[SA, [60.844378703000075, 29.858178610000067],..."
3,AL,2005,1.789692e+10,#8B0000,"{'AL': 45.0, 'Total': 45.0}","[[[19.747765747000074, 42.57890085900007], [19...",Polygon,6. Developing region,4. Lower middle income,Albania,Albania,Sovereign country,[]
4,BD,2015,5.380000e+11,#98FB98,"{'TJ': 11.0, 'Total': 11.0}","[[[[91.9387313160001, 21.714829820000105], [91...",MultiPolygon,7. Least developed region,5. Low income,Bangladesh,Bangladesh,Sovereign country,"[TJ, [88.37251753700016, 26.61160675100011], [..."

In [84]:
finalJson = df_to_geojson(globeFinal, cols)
# for feature in finalJson['features']:
Trafficking.insert_many(finalJson['features'])

In [88]:
results = Trafficking.find("{Properties['Year']":2013})
for result in results:
    print(result)