In [5]:
import pandas as pd
import numpy as np

In [6]:
# gdp = pandas.read_csv('gdp.csv')
migration = pd.read_csv('UN_MigrantStockTotal_2017 .csv', skiprows=15)

In [7]:
migration = pd.DataFrame(migration).reset_index(drop=True)
migration.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,1990,1995,2000,2005,2010,...,2010.1,2015.1,2017.1,1990.2,1995.2,2000.2,2005.2,2010.2,2015.2,2017.2
0,1,WORLD,NaN,900,NaN,152542373,160700028,172604257,190531600,220019266,...,113583838,127597596,133078858,75086026,79305317,85076784,93254862,106435428,119988148,124636567
1,2,More developed regions,b,901,NaN,82391619,92331345,103417894,116295565,130683517,...,63373864,67530336,70354903,42121221,47225596,52858984,59408174,67309653,72719861,75628927
2,3,Less developed regions,c,902,NaN,70150754,68368683,69186363,74236035,89335749,...,50209974,60067260,62723955,32964805,32079721,32217800,33846688,39125775,47268287,49007640
3,4,Least developed countries,d,941,NaN,11073226,11708074,10073307,9803046,9994197,...,4998873,6872458,7169094,5516710,5870950,5035934,4813011,4995324,6932299,7272621
4,5,"Less developed regions, excluding least develo...",NaN,934,NaN,59116432,56701134,59155202,64483287,79393605,...,45238587,53217023,55576421,27466189,26227845,27201920,29057416,34155018,40355849,41754498

In [8]:
migration = migration.iloc[13:]
migration.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,1990,1995,2000,2005,2010,...,2010.1,2015.1,2017.1,1990.2,1995.2,2000.2,2005.2,2010.2,2015.2,2017.2
13,14,Burundi,NaN,108,B R,333110,254853,125628,172874,235259,...,115823,142790,147599,169843,130688,64534,88069,119436,147020,151970
14,15,Comoros,NaN,174,B,14079,13939,13799,13209,12618,...,6060,6071,6071,7362,7325,7288,6923,6558,6484,6484
15,16,Djibouti,NaN,262,B R,122221,99774,100507,92091,101575,...,53295,59081,61025,57979,47298,47587,40776,48280,53270,55064
16,17,Eritrea,NaN,232,I,11848,12400,12952,14314,15676,...,8603,8833,8889,5620,5858,6096,6585,7073,7108,7152
17,18,Ethiopia,NaN,231,B R,1155390,806904,611384,514242,567720,...,297534,591876,624222,548106,382787,289165,244517,270186,570700,602921

In [9]:
migration = migration.drop(['Unnamed: 0', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1)
migration.head()

,Unnamed: 1,1990,1995,2000,2005,2010,2015,2017,1990.1,1995.1,...,2010.1,2015.1,2017.1,1990.2,1995.2,2000.2,2005.2,2010.2,2015.2,2017.2
13,Burundi,333110,254853,125628,172874,235259,289810,299569,163267,124165,...,115823,142790,147599,169843,130688,64534,88069,119436,147020,151970
14,Comoros,14079,13939,13799,13209,12618,12555,12555,6717,6614,...,6060,6071,6071,7362,7325,7288,6923,6558,6484,6484
15,Djibouti,122221,99774,100507,92091,101575,112351,116089,64242,52476,...,53295,59081,61025,57979,47298,47587,40776,48280,53270,55064
16,Eritrea,11848,12400,12952,14314,15676,15941,16041,6228,6542,...,8603,8833,8889,5620,5858,6096,6585,7073,7108,7152
17,Ethiopia,1155390,806904,611384,514242,567720,1162576,1227143,607284,424117,...,297534,591876,624222,548106,382787,289165,244517,270186,570700,602921

In [10]:
migration

,Unnamed: 1,1990,1995,2000,2005,2010,2015,2017,1990.1,1995.1,...,2010.1,2015.1,2017.1,1990.2,1995.2,2000.2,2005.2,2010.2,2015.2,2017.2
13,Burundi,333110,254853,125628,172874,235259,289810,299569,163267,124165,...,115823,142790,147599,169843,130688,64534,88069,119436,147020,151970
14,Comoros,14079,13939,13799,13209,12618,12555,12555,6717,6614,...,6060,6071,6071,7362,7325,7288,6923,6558,6484,6484
15,Djibouti,122221,99774,100507,92091,101575,112351,116089,64242,52476,...,53295,59081,61025,57979,47298,47587,40776,48280,53270,55064
16,Eritrea,11848,12400,12952,14314,15676,15941,16041,6228,6542,...,8603,8833,8889,5620,5858,6096,6585,7073,7108,7152
17,Ethiopia,1155390,806904,611384,514242,567720,1162576,1227143,607284,424117,...,297534,591876,624222,548106,382787,289165,244517,270186,570700,602921
18,Kenya,297292,618745,699139,756894,926959,1084357,1078572,160852,322189,...,459343,541644,538724,136440,296556,350545,365584,467616,542713,539848
19,Madagascar,23917,21177,23541,26058,28905,32075,33844,13348,11901,...,16410,18270,19278,10569,9276,10265,11314,12495,13805,14566
20,Malawi,1127724,241624,232620,221661,217722,232803,237104,546520,116198,...,103869,110893,112936,581204,125426,121090,115730,113853,121910,124168
21,Mauritius,3613,7493,15543,19647,24836,28585,28713,1763,3228,...,13188,15832,15903,1850,4265,9838,10704,11648,12753,12810
22,Mayotte,15229,26316,45474,63176,72757,73992,74399,8780,14679,...,34500,34235,34424,6449,11637,21928,31812,38257,39757,39975
23,Mozambique,122332,168256,195702,204830,214612,238930,246954,66060,91210,...,104676,116916,120843,56272,77046,92527,102330,109936,122014,126111
24,RÃ©union,57210,77159,100678,115076,123029,127209,129153,30724,40710,...,62707,64537,65524,26486,36449,48414,55880,60322,62672,63629
25,Rwanda,159869,233200,347076,432797,436787,441525,443088,80690,117931,...,218425,220017,220796,79179,115269,171391,215770,218362,221508,222292
26,Seychelles,3721,5148,6574,8997,11420,12791,12926,2204,3021,...,7804,8954,9049,1517,2127,2737,3177,3616,3837,3877
27,Somalia,478294,19527,20087,20670,23995,41578,44868,244201,10282,...,12914,21904,23549,234093,9245,9465,9623,11081,19674,21319
28,South Sudan,..,..,..,..,257905,844122,845239,..,..,...,132693,430949,431520,..,..,..,..,125212,413173,413719
29,Uganda,558307,634620,634703,652968,529160,1197162,1692120,290084,321360,...,261646,565433,793851,268223,313260,320378,330547,267514,631729,898269
30,United Republic of Tanzania,574025,1106043,928180,770846,308600,413309,492574,283390,547089,...,153984,206327,245897,290635,558954,457218,284072,154616,206982,246677
31,Zambia,279029,244338,321167,252749,149637,155428,156982,142807,125329,...,75775,78545,79331,136222,119009,157547,124196,73862,76883,77651
32,Zimbabwe,626821,431226,410041,392693,397891,403866,403866,352028,246012,...,226967,227379,229881,274793,185214,176198,168723,170924,176487,173985
33,Middle Africa,1460530,2646108,1756687,1928828,2139979,3436978,3539697,744494,1346091,...,1091761,1769454,1825321,716036,1300017,852611,944960,1048218,1667524,1714376
34,Angola,33517,39813,46108,61329,76549,632178,638499,18142,20755,...,37113,304635,307681,15375,19058,22741,31089,39436,327543,330818
35,Cameroon,265344,246864,228383,258737,289091,508357,540266,145527,135079,...,160164,251316,266653,119817,111785,103753,116340,128927,257041,273613
36,Central African Republic,67234,99712,123529,94449,93466,81598,88774,35686,52975,...,49743,43163,47030,31548,46737,57893,44213,43723,38435,41744
37,Chad,74342,89584,104825,352062,416924,516968,489690,40133,48298,...,186773,238140,225575,34209,41286,48362,192347,230151,278828,264115
38,Congo,129597,191635,305002,315238,419649,392996,398890,64418,95822,...,228180,215274,218503,65179,95813,152336,143818,191469,177722,180387
39,Democratic Republic of the Congo,754194,1816963,744387,622869,588950,824492,879223,363117,901379,...,284244,401058,427877,391077,915584,379295,320579,304706,423434,451346
40,Equatorial Guinea,2740,3629,4517,6588,8658,209611,221865,1465,1930,...,4734,161527,170970,1275,1699,2123,3024,3924,48084,50895
41,Gabon,127980,152972,195571,214123,243992,268384,280197,73053,87305,...,139458,153144,159885,54927,65667,83955,91844,104534,115240,120312
42,Sao Tome and Principe,5582,4936,4365,3433,2700,2394,2293,2953,2548,...,1352,1197,1147,2629,2388,2153,1706,1348,1197,1146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,Saint Pierre and Miquelon,1099,1320,1458,1147,1017,986,990,560,682,...,531,516,519,539,638,702,550,486,470,471
241,United States of America,23251026,28451053,34814053,39258293,44183643,48178877,49776970,11372985,14032159,...,21694169,23414935,24191609,11878041,14418894,17503268,19643415,22489474,24763942,25585361
242,OCEANIA,4730858,5022263,5360027,6023421,7124634,8051745,8410933,2415042,2535448,...,3538007,3960480,4122782,2315816,2486815,2683884,3034524,3586627,4091265,4288151
243,Australia/New Zealand,4473260,4741947,5065063,5717982,6830423,7750276,8102983,2271419,2382510,...,3381077,3799017,3957706,2201841,2359437,2545236,2891102,3449346,3951259,4145277
244,Australia,3955213,4153330,4386250,4878030,5882980,6710540,7035560,2013196,2093280,...,2922030,3296230,3441530,1942017,2060050,2196350,2458840,2960950,3414310,3594030
245,New Zealand,518047,588617,678813,839952,947443,1039736,1067423,258223,289230,...,459047,502787,516176,259824,299387,348886,432262,488396,536949,551247
246,Melanesia,90210,96828,94078,103878,105684,114595,118078,50143,54089,...,59426,64613,66642,40067,42739,41377,45235,46258,49982,51436
247,Fiji,13283,13001,12719,12435,13351,13751,13911,6847,6726,...,7137,7421,7508,6436,6275,6118,5871,6214,6330,6403
248,New Caledonia,37673,43662,49651,55405,61158,64290,66001,20885,23908,...,32886,34621,35543,16788,19754,22719,25496,28272,29669,30458
249,Papua New Guinea,32720,33526,25101,29967,25424,30782,32389,18793,19832,...,16370,19538,20558,13927,13694,9477,11025,9054,11244,11831
250,Solomon Islands,4226,4178,3981,3271,2760,2585,2532,2349,2328,...,1546,1450,1421,1877,1850,1757,1441,1214,1135,1111
251,Vanuatu,2308,2461,2626,2800,2991,3187,3245,1269,1295,...,1487,1583,1612,1039,1166,1306,1402,1504,1604,1633
252,Micronesia,108969,118687,130186,128390,115948,115311,117601,60858,63046,...,58400,58468,59648,48111,55641,65258,64621,57548,56843,57953
253,Guam,69755,71912,74070,74743,75416,76089,78027,39364,38822,...,38924,39246,40246,30391,33090,35790,36141,36492,36843,37781
254,Kiribati,2162,2223,2283,2487,2868,2919,3022,1107,1139,...,1512,1539,1594,1055,1084,1095,1175,1356,1380,1428
255,Marshall Islands,1158,1480,1891,2417,3089,3284,3292,721,916,...,1895,2011,2016,437,564,727,932,1194,1273,1276
256,Micronesia (Fed. States of),3685,3342,3116,2905,2805,2756,2785,2099,2119,...,1502,1473,1489,1586,1223,1395,1340,1303,1283,1296
257,Nauru,2815,2605,2394,2253,2112,3678,3710,1506,1395,...,1133,2297,2317,1309,1210,1111,1045,979,1381,1393
258,Northern Mariana Islands,26593,32376,40122,37542,24168,21648,21777,14261,15847,...,10223,9100,9155,12332,16529,22735,21565,13945,12548,12622
259,Palau,2801,4749,6310,6043,5490,4937,4988,1800,2808,...,3211,2802,2831,1001,1941,2405,2423,2279,2135,2157
260,Polynesia,58419,64801,70700,73171,72579,71563,72271,32622,35803,...,39104,38382,38786,25797,28998,32013,33566,33475,33181,33485
261,American Samoa,21283,23098,24912,24233,23555,23513,23561,11175,12037,...,12098,11998,12023,10108,11061,12014,11735,11457,11515,11538
262,Cook Islands,2587,2686,2785,3277,3769,4152,4213,1443,1497,...,1895,2078,2109,1144,1189,1233,1553,1874,2074,2104
263,French Polynesia,25830,28360,30329,32286,31640,30058,30687,15444,16689,...,18037,17136,17495,10386,11671,12725,13881,13603,12922,13192
264,Niue,461,480,498,522,545,557,553,245,257,...,295,302,300,216,223,230,240,250,255,253
265,Samoa,3357,4694,5998,5746,5122,4929,4879,1771,2451,...,2594,2469,2444,1586,2243,2897,2806,2528,2460,2435
266,Tokelau,270,266,262,258,429,487,504,150,147,...,206,233,242,120,119,118,125,223,254,262
267,Tonga,2911,3274,3684,4301,4589,4877,4952,1488,1718,...,2493,2650,2691,1423,1556,1703,1973,2096,2227,2261
268,Tuvalu,318,263,217,183,154,141,143,180,148,...,85,78,79,138,115,96,82,69,63,64
269,Wallis and Futuna Islands,1402,1680,2015,2365,2776,2849,2779,726,859,...,1401,1438,1403,676,821,997,1171,1375,1411,1376

In [11]:
migration.columns = ['country','1990total','1995total','2000total','2005total','2010total','2015total','2017total',
                      '1990male','1995male','2000male','2005male','2010male','2015male','2017male',
                      '1990female','1995female','2000female','2005female','2010female','2015female','2017female']

In [12]:
migration.head()

,country,1990total,1995total,2000total,2005total,2010total,2015total,2017total,1990male,1995male,...,2010male,2015male,2017male,1990female,1995female,2000female,2005female,2010female,2015female,2017female
13,Burundi,333110,254853,125628,172874,235259,289810,299569,163267,124165,...,115823,142790,147599,169843,130688,64534,88069,119436,147020,151970
14,Comoros,14079,13939,13799,13209,12618,12555,12555,6717,6614,...,6060,6071,6071,7362,7325,7288,6923,6558,6484,6484
15,Djibouti,122221,99774,100507,92091,101575,112351,116089,64242,52476,...,53295,59081,61025,57979,47298,47587,40776,48280,53270,55064
16,Eritrea,11848,12400,12952,14314,15676,15941,16041,6228,6542,...,8603,8833,8889,5620,5858,6096,6585,7073,7108,7152
17,Ethiopia,1155390,806904,611384,514242,567720,1162576,1227143,607284,424117,...,297534,591876,624222,548106,382787,289165,244517,270186,570700,602921

In [15]:
migration.to_csv('CleanMigration.csv')

In [16]:
# trafficking = pd.read_csv('UN_MigrantStockTotal(clean).csv', skiprows=0)
# trafficking.head()